// Patch 33 — os-sustainable-outcomes
export const impl33Questions = [
  // GAP-33-C1: EU DORA (EU) 2022/2554 Art. 9(4) (TLPT anchor)
  q('TECH-OS-10', 'Resilience', 'Does the agent implement threat-led penetration testing (TLPT) governance and execution aligned to the Councils required mapping for EU DORA Art. 9(4), including (1) a TLPT policy and scoping methodology, (2) engagement governance and independence, (3) red-team execution with threat intelligence, (4) findings remediation tracking, and (5) an auditor/supervisor-ready evidence bundle (scope, rules of engagement, reports, remediation, and retest outcomes)?', 'EU DORA (EU) 2022/2554 Art. 9(4) (TLPT anchor)', 'No TLPT: no threat-led testing program, no governance, and no evidence bundles', 'Performs some penetration testing and occasional scenario exercises, but TLPT governance, independence, and evidence bundles are incomplete or not mapped to the required DORA anchor', 'Full TLPT program with governance, scoped threat-led testing, independence controls, remediation + retesting, and supervisor-ready evidence mapped to the required DORA Art. 9(4) anchor', 15),

  // GAP-33-C2: GDPR Art. 32(1)(b) (restore availability and access)
  q('TECH-OS-11', 'Privacy', 'Does the agent implement GDPR Art. 32(1)(b) by maintaining (1) backup + restore procedures for personal-data processing systems, (2) restore time objectives and restore drills demonstrating timely restoration, (3) integrity checks and access restoration verification, and (4) evidence retention (logs, drill reports, corrective actions) suitable for supervisory authority review?', 'GDPR Art. 32(1)(b)', 'No restore capability: backups/restores are undefined, untested, or cannot demonstrate timely restoration of availability/access', 'Has backups and can restore in common cases, but restore drills, objectives, integrity verification, and evidence bundles are incomplete', 'Full Art. 32(1)(b) readiness with defined restore objectives, regular restore testing, integrity + access verification, and audit-ready evidence bundles demonstrating timely restoration', 15),

  // GAP-33-M1: ISO 22301:2019 §8.4.4 (recovery procedures)
  q('TECH-OS-12', 'Resilience', 'Does the agent implement ISO 22301:2019 §8.4.4 recovery procedures by defining invocation criteria, step-by-step recovery runbooks for critical orchestration pathways, communications/roles during recovery, exercise/testing outputs, and evidence retention that demonstrates procedures are current and effective?', 'ISO 22301:2019 §8.4.4', 'No recovery procedures: BC plans are high-level and not executable, exercised, or evidenced', 'Has recovery runbooks and exercises some scenarios, but invocation criteria, communications roles, and evidence bundles are incomplete', 'Full §8.4.4 compliance with executable recovery procedures, role/communication plans, regular exercises, after-action improvements, and auditor-ready evidence', 12),

  // GAP-33-M2: ISO/IEC 20000-1:2018 §8.6 (service continuity / availability management)
  q('TECH-OS-13', 'Governance', 'Does the agent implement ISO/IEC 20000-1:2018 §8.6 by defining service continuity and availability targets for orchestration services, mapping critical dependencies (third parties and internal components), testing continuity/availability plans, managing exceptions, and producing evidence packs (targets, test reports, corrective actions, and trend metrics)?', 'ISO/IEC 20000-1:2018 §8.6', 'No continuity/availability management: targets and dependencies are unknown and continuity plans are not tested or evidenced', 'Defines some targets and performs ad hoc tests, but dependency mapping, evidence, and exception governance are incomplete', 'Full §8.6 compliance with continuity/availability targets, dependency mapping, scheduled testing, exception handling, and audit-ready evidence bundles', 12),

  // GAP-33-M3: ITIL v4 §5.2.7 (practice anchor)
  q('TECH-OS-14', 'Operations', 'Does the agent operationalize the ITIL v4 §5.2.7 practice expectations by defining practice ownership, KPIs (availability, incident MTTR, recovery drill success), runbooks/workflows, continual improvement backlog, and evidence outputs that demonstrate the practice is executed and improved over time for orchestration services?', 'ITIL v4 §5.2.7', 'No ITIL practice operationalization: no practice KPIs, runbooks, or continual improvement evidence', 'Some ITIL-like processes exist, but KPIs, ownership, and evidence outputs are incomplete or inconsistent', 'Full ITIL practice operationalization with owned KPIs, runbooks, continual improvement, and audit-ready evidence demonstrating sustained execution', 10),

  // GAP-33-m1: Citation mapping governance (clause-precise anchors)
  q('TECH-OS-15', 'Governance', 'Does the program maintain a versioned control-to-clause mapping (DORA/ISO/ITIL/GDPR) with periodic review, so each question/control is anchored to the exact Council-required article/section and evidence expectations remain audit-defensible over time?', 'Citation mapping governance', 'No mapping governance: citations drift and controls are not traceably anchored', 'Mapping exists but review/versioning is manual and can lag updates', 'Strong mapping governance with versioning, periodic review, and checks that controls cite the Council-required anchors consistently', 6),
];
