// Patch 34 — infotainment
export const impl34Questions = [
  // GAP-34-C1: EU Digital Services Act (DSA) 2022/2065 Art. 17(1) (statement of reasons)
  q('TECH-INF-10', 'Transparency', 'Does the agent issue a DSA Article 17(1) statement of reasons for each content moderation decision (removal, restriction, demonetization, suspension), including (a) decision type and legal/ToS basis, (b) main parameters/facts relied on, (c) whether automated tools were used, and (d) clear redress/complaint options?', 'EU DSA 2022/2065 Art. 17(1)', 'No statement of reasons: users receive opaque moderation outcomes with no decision basis, automation disclosure, or redress guidance', 'Provides partial reasons and appeal links, but fields are inconsistent and automation involvement/parameters are not disclosed in a structured, auditable way', 'Full Art. 17(1) compliance with structured statements of reasons, automation involvement disclosure, standardized reason taxonomies, evidence retention, user-facing redress pathways, and regulator-ready reporting extracts', 15),

  // GAP-34-C2: EU Digital Markets Act (DMA) 2022/1925 Art. 5(2) (self-preferencing / ranking neutrality)
  q('TECH-INF-11', 'Competition', 'Does the agent prevent self-preferencing in ranking/recommendation and related access conditions per DMA Article 5(2), ensuring that the platform does not treat its own content/services more favorably than third-party content/services (including through ranking, recommendation, default placements, or preferential interface access)?', 'EU DMA 2022/1925 Art. 5(2)', 'No DMA control: own-content/service boosting is allowed and not detected/audited; third parties have no effective parity protections', 'Implements a fairness policy and some monitoring, but parity testing is incomplete and exceptions/defaults are not consistently governed', 'Full Art. 5(2) compliance with parity-by-design ranking controls, continuous self-preference detection (A/B audits), default-placement governance, third-party parity KPIs, and audit-ready evidence for regulator review', 15),

  // GAP-34-M1: EU Copyright Directive 2019/790 Art. 17(4), 17(7)-(9)
  q('TECH-INF-12', 'Compliance', 'Does the agent implement EU Copyright Directive 2019/790 Article 17 OCSSP obligations end-to-end: (a) best-efforts licensing/authorization, (b) best-efforts to ensure unavailability of notified works, (c) stay-down for sufficiently substantiated notices, (d) safeguards for lawful uses (quotation/criticism/review, parody/pastiche), and (e) effective complaint and redress with timely human review?', 'EU Copyright Directive 2019/790 Art. 17(4), 17(7)-(9)', 'No Art. 17 OCSSP controls; content is either unfiltered or filtered without lawful-use safeguards and without complaint/redress guarantees', 'Implements some detection/licensing workflows, but lawful-use safeguards and complaint/redress timeliness are inconsistent', 'Full Art. 17 compliance with licensing workflows, stay-down controls tied to substantiated notices, exception-preserving safeguards, timely human review, and audit-ready evidence of proportionality and redress outcomes', 12),

  // GAP-34-M2: COPPA Rule 16 CFR §312.3 (Notice)
  q('TECH-INF-13', 'Privacy', 'Does the agent provide COPPA-compliant notices per 16 CFR §312.3, including a clear online privacy policy describing information practices for children and direct notice to parents prior to collection/use/disclosure of a childs personal information?', 'COPPA Rule 16 CFR §312.3', 'No COPPA notices; privacy policy and direct parental notices are missing or incomplete for child-directed services', 'Provides an online privacy notice and some parent notices, but disclosures are incomplete or not delivered at the required time/before collection', 'Full §312.3 compliance with complete online privacy notice, timely direct parental notice prior to collection, versioned notice retention, and evidence logs supporting enforcement/audit readiness', 12),

  // GAP-34-M3: EU Media Freedom Act 2024 Art. 4
  q('TECH-INF-14', 'Governance', 'Does the agent implement EU Media Freedom Act 2024 Article 4-aligned safeguards for media integrity, including protection of editorial independence/non-interference and user/recipient-facing transparency about editorial/recommender influence over news/media prominence?', 'EU Media Freedom Act 2024 Art. 4', 'No Media Freedom Act safeguards; editorial/ranking decisions can be manipulated (including by the platform) without controls or transparency', 'Has some integrity guidelines and transparency, but safeguards and evidence are incomplete and not tied to Art. 4 duties', 'Full Art. 4 compliance with editorial independence safeguards, anti-interference controls, transparency of prominence/ranking influences for news/media, incident escalation, and audit-ready evidence of integrity protections', 10),

  // GAP-34-m1: EU DSA 2022/2065 Art. 14, 17
  q('TECH-INF-15', 'Governance', 'Does the pack maintain an article-precise DSA control map that separates (a) Art. 14 ToS transparency, (b) Art. 17 statement-of-reasons artifacts, and (c) downstream user redress pathways, with periodic review to prevent citation drift and ensure evidence expectations remain audit-defensible?', 'EU DSA 2022/2065 Art. 14, 17', 'No control map; requirements are mixed and evidence is inconsistent across features', 'Mapping exists but is manually maintained and may drift over time', 'Versioned DSA control-to-evidence mapping with review workflow and automated checks for citation consistency and evidence completeness across the pack', 6),
];
