// Implementation patch for material-to-machines
// All new q() calls extracted from audit gaps
export const impl03Questions = [
  // GAP-03-C1: EU Machinery Regulation (EU) 2023/1230 Art. 10 (EHSR via Annex III)
  q('ENV-MM-10', 'Safety', 'Does the agent verify that machinery design, integration changes, and software/AI updates maintain conformity with the EU Machinery Regulation (EU) 2023/1230 Article 10 obligation to meet Essential Health and Safety Requirements (EHSR) (Annex III), including safety of control systems and foreseeable misuse?', 'EU Machinery Regulation (EU) 2023/1230 Art. 10; Annex III (EHSR)', 'No EHSR mapping; safety requirements are not traced to design controls or update/release decisions', 'Maintains an EHSR checklist and basic traceability to design controls, but software/AI changes are not consistently re-assessed for safety impact', 'Continuous EHSR compliance-by-design with requirements traceability, safety-function validation for software/AI changes, change-impact assessment gates, and authority-ready technical documentation updates aligned to Annex III', 15),

  // GAP-03-C2: IEC 62443-3-3 SR 1.1 (Identification and Authentication Control)
  q('ENV-MM-11', 'Security', 'Does the agent implement and continuously verify Identification and Authentication Control per IEC 62443-3-3 SR 1.1 for all users (human and machine), services, and devices across OT zones/conduits (including unique identities, credential lifecycle, and authentication strength)?', 'IEC 62443-3-3 SR 1.1', 'Shared accounts/weak authentication; device/service identities are unmanaged and not auditable', 'Unique user IDs and basic authentication are implemented, but service/device identity, credential rotation, and coverage across zones is incomplete', 'Full SR 1.1 implementation with unique identities for users/services/devices, strong authentication, credential rotation, secure enrollment, continuous verification, and audit-ready evidence mapped to target security level', 12),

  // GAP-03-M1: ISO 45001:2018 §8.1.3 (Management of change)
  q('ENV-MM-12', 'Safety', 'Does the agent manage OH&S-related change control per ISO 45001:2018 §8.1.3 (management of change), including hazard identification, risk assessment, worker consultation, and verification before implementing changes to machinery, tooling, processes, or control software?', 'ISO 45001:2018 §8.1.3', 'No formal change management for OH&S; changes are applied without documented hazard/risk review', 'Performs change reviews and risk assessments for major changes, but coverage is inconsistent and worker consultation/evidence capture is incomplete', 'Closed-loop OH&S change management with automated hazard prompts, risk controls selection, worker consultation records, pre-startup safety verification, and auditable change approval gates', 10),

  // GAP-03-M2: EU Ecodesign Regulation (EU) 2024/1781 Art. 7 (repairability)
  q('ENV-MM-13', 'Sustainability', 'Does the agent operationalize repairability requirements per EU Ecodesign Regulation (EU) 2024/1781 Article 7 (repair access, spare parts/consumables availability, repair information, and design for disassembly), and gate design releases against repairability constraints?', 'EU Ecodesign Regulation (EU) 2024/1781 Art. 7', 'No repairability controls; design decisions do not manage spare parts, disassembly, or repair information availability', 'Generates repairability guidance and partial spare-parts lists, but compliance is not enforced as a release gate and evidence is incomplete', 'Repairability-by-design with enforceable constraints, automated spare-parts availability rules, disassembly time/steps scoring, repair information publication workflows, and compliance evidence packs aligned to delegated-act requirements', 10),

  // GAP-03-m1: RoHS Directive 2011/65/EU Art. 4
  q('ENV-MM-14', 'Compliance', 'Does the agent enforce RoHS Directive 2011/65/EU Article 4 by gating release/placing-on-the-market decisions on product-level RoHS compliance evidence (including BOM aggregation, supplier declarations, test evidence, and exemption applicability tracking)?', 'RoHS Directive 2011/65/EU Art. 4', 'No release gate; products are placed on the market without consolidated RoHS compliance evidence and exemption control', 'Aggregates BOM declarations and flags issues, but exemption applicability and product-level sign-off are manual and inconsistently retained', 'Automated product-level RoHS compliance gating with evidence linkage, exemption lifecycle management (Annex III/IV), sampling/testing integration, and audit-ready technical file exports', 8),
];
