// Patch 22 — higher-education
export const impl22Questions = [
  // GAP-22-C1: FERPA 34 CFR §99.31(a)(1) (disclosure to school officials with legitimate educational interests)
  q('EDU-HE-10', 'Compliance', 'Does the agent implement FERPA 34 CFR §99.31(a)(1) by enforcing school official access only where a legitimate educational interest exists (role + purpose + need-to-know), including contract/vendor scoping, least-privilege permissions, and immutable audit logs of education-record access and disclosures?', 'FERPA 34 CFR §99.31(a)(1)', 'No legitimate-interest enforcement; education records are accessible to staff/vendors without a documented legitimate educational interest basis or auditable access controls', 'Implements role-based access and some logging, but legitimate-interest determinations, vendor scoping, and disclosure/audit exports are incomplete or inconsistent', 'End-to-end §99.31(a)(1) compliance with policy-based legitimate-interest checks, vendor/service-provider constraints, least-privilege access, time-bounded access where appropriate, and immutable access/disclosure logs with exportable evidence for FERPA complaints/audits', 15),

  // GAP-22-C2: Title IX 34 CFR §106.45 (grievance process requirements)
  q('EDU-HE-11', 'Compliance', 'If the agent supports Title IX reporting, intake, investigation, or decision support, does it comply with 34 CFR §106.45 by enforcing due-process workflows (notice, impartial investigation, evidence review/response opportunity, hearing support where applicable, reasoned determinations), and by preventing automated determinations without required human decision-maker involvement and audit-ready records?', 'Title IX 34 CFR §106.45', 'No Title IX due-process support; AI triage/case workflows are ad-hoc, biased, or lack evidence review rights and auditable determinations', 'Implements a case workflow and human review, but evidence review rights, impartiality safeguards, and decision documentation are incomplete or inconsistently enforced', 'Full §106.45 operationalization with structured due-process steps, role separation/impartiality controls, evidence-bundle management, mandatory human determinations, and immutable logs of notices, evidence access, responses, and final determinations', 15),

  // GAP-22-C3: UNESCO Higher Education (2022) §4 (academic integrity)
  q('EDU-HE-12', 'Governance', 'Does the agent operationalize UNESCO Higher Education (2022) §4 academic integrity by supporting (1) AI-use disclosure/attribution norms, (2) assessment design options that preserve validity, (3) misconduct detection as decision support (not sole basis), (4) fair due-process investigation and appeals, and (5) continuous integrity improvement reporting?', 'UNESCO Higher Education (2022) §4', 'No UNESCO §4 loop; integrity relies on ad-hoc detection or punitive actions without policy alignment, fair process, or improvement evidence', 'Has integrity policies and some detection tooling, but disclosure norms, due process, and continuous improvement evidence are incomplete', 'Full UNESCO §4 integrity system with policy-to-workflow mapping, disclosure and attribution standards, assessment redesign guidance, human-reviewed misconduct pathways with appeals, and auditable integrity metrics + improvement actions over time', 12),

  // GAP-22-M1: AACSB Business Accreditation Standards — Standard 4 (Curriculum)
  q('EDU-HE-13', 'Compliance', 'Does the agent maintain AACSB Standard 4 curriculum governance by ensuring AI-assisted curriculum changes remain aligned to program learning goals, required content coverage, and documented curriculum-management processes (including faculty oversight/approvals and evidence artifacts suitable for accreditation review)?', 'AACSB Standard 4 (Curriculum)', 'No AACSB S4 governance; AI changes curriculum content without documented faculty oversight or learning-goal alignment evidence', 'Tracks curriculum versions and approvals, but learning-goal alignment and accreditation evidence artifacts are partial or not audit-ready', 'Full AACSB S4 readiness with curriculum change control, faculty governance sign-offs, learning-goal mapping, required-content checks, and accreditation-ready evidence bundles showing curriculum integrity over time', 12),

  // GAP-22-M2: EU AI Act Annex III §3 (education and vocational training)
  q('EDU-HE-14', 'Governance', 'For EU AI Act Annex III §3 high-risk uses beyond admissions (e.g., assessment, proctoring, progression), does the agent implement lifecycle controls comparable to high-risk requirements (risk management, data governance, logging/technical documentation, and meaningful human oversight) and package evidence suitable for conformity assessment and oversight inquiries?', 'EU AI Act Annex III §3 (education)', 'No lifecycle controls outside admissions; assessment/proctoring AI lacks documented risk management, data governance, logging, and oversight criteria', 'Implements human review and some logs, but risk management and data governance for assessment/proctoring are incomplete or not evidence-grade', 'Comprehensive Annex III §3 operationalization for assessment/proctoring/progression with risk management, dataset governance, event logging, technical documentation, and human oversight criteria with auditable evidence packaging', 12),

  // GAP-22-m1: FERPA 34 CFR §99.31 (exceptions) + de-identification expectations (practice)
  q('EDU-HE-15', 'Traceability', 'Does the agent enforce purpose limitation for education records and provide governed de-identification/pseudonymization pathways for analytics/research use cases (including provenance, approvals, and access logging), consistent with FERPA exception documentation expectations?', 'FERPA 34 CFR §99.31 (documentation expectations)', 'No governance for secondary use; datasets are reused across purposes without de-identification controls or approvals', 'Some de-identification exists, but approvals/provenance and access logging are incomplete', 'Full secondary-use governance with de-identification/pseudonymization pipelines, approval workflows, provenance tracking, and immutable access logs for analytics/research datasets', 8),
];
