// Patch 37 — dance-of-democracy
export const impl37Questions = [
  // GAP-37-C1: EU AI Act Art. 5(1)(b) (prohibited exploitation of vulnerabilities; Council-required anchor)
  q('GOV-DD-10', 'Compliance', 'Does the agent strictly comply with EU AI Act Article 5(1)(b) by preventing any electoral AI technique that exploits vulnerabilities (age, disability, or social/economic situation) to materially distort voting-related behavior, including coercive targeting, suppression messaging, or undue influence that undermines free political choice?', 'EU AI Act Art. 5(1)(b)', 'No safeguards: electoral AI can target vulnerable groups with coercive or exploitative messaging to distort behavior', 'Has basic policies and some guardrails, but vulnerability exploitation is not systematically detected, tested, or prevented across targeting and content-generation pipelines', 'Full Art. 5(1)(b) compliance with vulnerability-exploitation threat modeling, pre-deployment testing/red-teaming, targeting restrictions, election-period heightened controls, monitoring for coercive patterns, and auditor-ready evidence of prohibited-practice prevention', 25),

  // GAP-37-C2: EU Digital Services Act (DSA) 2022/2065 Art. 34(1)(c) (systemic risks for electoral processes/civic discourse) + Art. 35 (mitigation)
  q('GOV-DD-11', 'Safety', 'For services in scope of DSA systemic-risk duties, does the agent perform a clause-precise DSA Article 34(1)(c) risk assessment for electoral processes and civic discourse (including recommender/ads systems, amplification dynamics, and coordinated inauthentic behavior) and implement DSA Article 35 mitigations with measurable effectiveness reporting during election periods?', 'EU DSA 2022/2065 Art. 34(1)(c), Art. 35', 'No election systemic-risk assessment or mitigation: risks to civic discourse/elections are unmanaged and unmeasured', 'Performs general misinformation review and some mitigations, but does not run an Art. 34(1)(c)-anchored assessment nor track Art. 35 mitigation effectiveness with election-period escalation', 'Full Art. 34(1)(c)/35 program with documented risk assessment, mitigation selection and effectiveness metrics, election-period escalation playbooks, independent review support, and regulator-ready evidence exports', 20),

  // GAP-37-C3: OSCE/ODIHR §3.2 (Council-required anchor)
  q('GOV-DD-12', 'Governance', 'Does the agent meet OSCE/ODIHR §3.2-aligned election technology integrity expectations by providing independent verification support (pre-election testing, audit access, observer-accessible evidence), verifiability of results processes, and transparent change-control over AI-influenced electoral workflows?', 'OSCE/ODIHR §3.2', 'No ODIHR-grade verifiability: no independent verification, limited audit access, and opaque AI influence over election workflows', 'Allows some audits and logs, but observer access, change-control transparency, and verifiability evidence are incomplete or inconsistently provided', 'Full §3.2 alignment with independent verification protocols, observer-accessible evidence packages, tamper-evident logs, strict change-control, and repeatable audit procedures for AI-influenced election operations', 20),

  // GAP-37-C4: GDPR Art. 9(1) (political opinions) and Art. 9(2)(d) (not-for-profit bodies exemption; Council-required anchor)
  q('GOV-DD-13', 'Privacy', 'Where political opinions (GDPR Art. 9(1)) are processed in electoral services, does the agent (a) determine and document whether GDPR Art. 9(2)(d) is applicable (not-for-profit body, legitimate activities, appropriate safeguards, no disclosure outside without consent), (b) enforce data minimization and access controls, and (c) prevent inferential political profiling beyond the chosen lawful basis with audit-ready evidence?', 'GDPR Art. 9(1), Art. 9(2)(d)', 'No Art. 9 governance: political opinion data is processed without a defensible Art. 9 basis, safeguards, or minimization', 'Has some special-category controls, but Art. 9(2)(d) applicability constraints, non-disclosure safeguards, and inferential profiling prevention are incomplete', 'Full Art. 9 governance with documented basis selection, enforceable safeguards/non-disclosure controls, minimization, strict access controls, DPIA/records linkage, and evidence exports for supervisory authority review', 15),

  // GAP-37-M1: Council of Europe CM/Rec(2017)5 (algorithmic systems)
  q('GOV-DD-14', 'Governance', 'Does the agent implement Council of Europe CM/Rec(2017)5-aligned accountability and remedy for electoral algorithmic systems, including clear responsibility assignment, oversight escalation, user-facing contestability/appeal pathways, and retention of evidence sufficient to support independent review during election periods?', 'CoE CM/Rec(2017)5', 'No accountability/remedy: electoral algorithmic decisions are opaque, unowned, and not meaningfully contestable', 'Provides limited appeals and some governance, but responsibilities, timelines, and evidence retention for independent review are incomplete', 'Full CM/Rec(2017)5 accountability with owned controls, escalation/oversight, contestability mechanisms, election-period SLAs, and audit-ready evidence supporting independent review and remedies', 10),

  // GAP-37-m1: Control-to-law citation governance (Council-required anchor precision)
  q('GOV-DD-15', 'Governance', 'Does the program maintain a versioned, Council-anchor-aligned control-to-law mapping for the Dance of Democracy pack (EU AI Act Art. 5(1)(b), DSA Art. 34(1)(c), OSCE/ODIHR §3.2, CoE CM/Rec(2017)5, GDPR Art. 9(2)(d)), with periodic review to prevent citation drift and ensure evidence expectations remain audit-defensible?', 'Citation mapping governance', 'No mapping governance: citations drift and requested anchors are inconsistently used', 'Mapping exists but updates are manual and inconsistently applied', 'Versioned control mapping with review workflow and automated checks for citation consistency across questions and outputs', 6),
];
