// Patch 23 — skills-training
export const impl23Questions = [
  // GAP-23-C1: law
  q('EDU-ST-10', 'Compliance', 'If used by (or on behalf of) a public entity VET provider, does the agent ensure ADA Title II §12132 compliance by providing equal access and reasonable modifications and auxiliary aids for learners with disabilities across (1) program access and admissions, (2) learning delivery, and (3) competency assessment (including alternative assessment formats and human review where needed)?', 'ADA Title II, 42 U.S.C. §12132', 'No ADA Title II controls: learner flows are inaccessible and there is no structured reasonable modification or auxiliary aid support for training or assessments', 'Provides some accessibility features and an accommodation request channel, but modifications and auxiliary aids and alternative assessment pathways are inconsistent or not auditable', 'End to end ADA Title II readiness with WCAG aligned accessible UX, auxiliary aid support, documented reasonable modification workflows, alternative assessment routing, and auditable accommodation decisions and outcomes for training and assessment', 15),

  // GAP-23-C2: law
  q('EDU-ST-11', 'Governance', 'Does the agent support ILO R195 §7 by enabling compliant training leave management (eligibility rules, leave requests and scheduling, non retaliation safeguards, documentation for employers and authorities, and equitable access for non standard workers), including audit ready records of leave decisions and participation outcomes?', 'ILO R195 (2004) §7', 'No training leave support: participation assumes learners can attend and there are no workflows for leave entitlement, scheduling constraints, or documentation', 'Provides basic scheduling and attendance tracking, but leave entitlements and non retaliation and audit ready documentation are incomplete', 'Full training leave operationalization with entitlement rule configuration, leave request routing, non retaliation controls, documentation templates, and audit logs linking leave approvals to training participation and outcomes', 12),

  // GAP-23-M1: law
  q('EDU-ST-12', 'Governance', 'Does the agent operationalize UNESCO TVET 2022 §4.2 by implementing a TVET quality and inclusion enablers loop (e.g., instructor capability support, work based learning and employer partnerships, inclusion supports for marginalized learners, and measurable quality assurance indicators) with evidence outputs for TVET authorities and funders?', 'UNESCO TVET 2022 §4.2', 'No UNESCO 2022 §4.2 operationalization: there is no defined quality and inclusion enablers loop or evidence reporting', 'Tracks some indicators (completion, satisfaction) and has informal partner inputs, but enablers and inclusion mechanisms are partial and not evidence grade', 'Full UNESCO 2022 §4.2 operationalization with defined QA indicators, instructor capability supports, employer and work based learning integration, inclusion supports, and auditable evidence reporting tied to continuous improvement actions', 12),

  // GAP-23-M2: law
  q('EDU-ST-13', 'Governance', 'Does the agent implement ISO 29990:2010 §4.2 needs analysis by capturing and validating (1) learner needs and prerequisites and constraints, (2) employer and labor market requirements, (3) accessibility and reasonable modification needs, and (4) stakeholder acceptance criteria, and then using these inputs to govern learning service design and evaluation?', 'ISO 29990:2010 §4.2', 'No needs analysis: learning services are generated or delivered without structured input validation or stakeholder requirement capture', 'Captures some requirements informally, but needs analysis is incomplete or not linked to design and evaluation decisions', 'Full ISO 29990 §4.2 compliance with structured needs analysis, stakeholder sign off, traceable linkage into learning design, and evidence outputs showing requirements to design to evaluation continuity', 12),

  // GAP-23-m1: law
  q('EDU-ST-14', 'Transparency', 'For AI influenced vocational training access, placement, or competency assessment decisions, does the agent provide meaningful human oversight and a learner contestation and appeal pathway (clear reasons, evidence review, and timely human reconsideration), consistent with high risk controls expected for Annex III §3(a) systems?', 'EU AI Act Art. 14; Annex III §3(a)', 'No contestation: AI driven placement and assessment outcomes are not explainable and cannot be appealed', 'Provides basic explanations and a manual appeal email address, but evidence review and human reconsideration SLAs are undefined', 'Full oversight and contestability with reason codes, evidence bundles, defined appeal workflow and SLAs, and auditable human reconsideration outcomes', 10),
];
