// Implementation patch for digital-payments — all gaps from audit
export const impl17Questions = [
  // GAP-17-C1: PCI DSS v4.0 Req. 6.4.3
  q('WLT-DP-10', 'Safety', 'For payment pages, does the agent enforce PCI DSS v4.0 Requirement 6.4.3 by maintaining an authorized script inventory, validating each script legitimacy (source/owner/purpose), implementing change detection and integrity controls (e.g., SRI/CSP/script hashing), and alerting or blocking on unauthorized or modified scripts that could capture payment data?', 'PCI DSS v4.0 Req. 6.4.3', 'No payment-page script governance: scripts are loaded without authorization controls or integrity monitoring, allowing silent skimming or exfiltration', 'Maintains a script inventory and basic CSP, but integrity or change detection and alerting are incomplete and not audit-ready', 'Full PCI 6.4.3 readiness with authorized-script allowlisting, continuous integrity monitoring (SRI/CSP/hashes), automated change approval workflows, real-time alerting or blocking for unauthorized scripts, and audit evidence bundles for assessor review', 15),

  // GAP-17-C2: EU DORA (EU) 2022/2554 Art. 17
  q('WLT-DP-11', 'Governance', 'Does the agent support EU DORA Article 17 ICT-related incident management by (1) classifying incidents against DORA materiality criteria, and (2) generating regulator-ready notifications including an initial notification within the required timeframe (commonly treated as ~4 hours from classification for major incidents), followed by intermediate and final reports with root cause, impact, and remediation updates?', 'EU DORA (EU) 2022/2554 Art. 17', 'No DORA incident reporting: incidents are handled operationally but are not classified or reported on DORA timelines with regulator-ready content', 'Classifies incidents and drafts reports, but timelines, required data fields, and evidence of submission are inconsistent or manual', 'Full DORA Art. 17 compliance with automated incident classification, 4-hour notification SLA tracking, templated initial, intermediate, and final reports, evidence retention of submissions and communications, and post-incident lessons-learned linkage to control improvements', 12),

  // GAP-17-M1: EBA RTS on SCA (EU) 2018/389 Art. 4
  q('WLT-DP-12', 'Compliance', 'Does the agent implement SCA RTS dynamic linking by cryptographically binding authentication to the specific transaction amount and payee (and ensuring integrity-protected display or confirmation of those elements to the payer), and by preventing post-authentication manipulation of amount or payee in both browser and app flows?', 'EBA RTS on SCA (EU) 2018/389 Art. 4 (dynamic linking)', 'No dynamic linking: MFA may be used but authentication is not bound to amount or payee and transaction details can be manipulated', 'Binds authentication to some transaction details and displays amount and payee, but integrity protections and manipulation detection are incomplete across channels', 'Full RTS dynamic linking with cryptographic binding to amount and payee, secure display and confirmation, channel-consistent enforcement (web/app), tamper detection, and audit logs demonstrating binding and user confirmation', 12),
];
