// Patch 26 — sustainable-communities
export const impl26Questions = [
  // GAP-26-C1: C40 Cities — 2030 net-zero / 1.5°C-aligned city climate action expectations
  q('MOB-SC-10', 'Sustainability', 'Does the agent manage a C40-aligned net-zero pathway with 1.5°C-consistent milestones to 2030 (sectoral emissions budgets for buildings/transport/waste, action tracking, financing readiness, and accountability reporting)?', 'C40 2030 net-zero (1.5°C-aligned pathways)', 'No net-zero pathway governance; actions are ad-hoc and not tied to sectoral budgets or 2030 milestones', 'Has a net-zero plan and some milestones, but sectoral budgeting, funding linkage, and accountability reporting are incomplete', 'Full C40-aligned pathway governance with sectoral budgets, quantified milestones to 2030, financed action portfolio tracking, progress dashboards, and third-party-verifiable accountability reporting', 15),

  // GAP-26-C2: Paris Agreement Art. 6
  q('MOB-SC-11', 'Governance', 'If the city uses cooperative approaches/carbon market mechanisms, does the agent enforce Paris Agreement Article 6 integrity controls (project MRV, authorization records, registry linkage, corresponding-adjustment awareness where applicable, and anti-double-counting checks)?', 'Paris Agreement Art. 6', 'No Art. 6 controls; carbon claims/credits are not governed and double counting risks are unmanaged', 'Tracks project MRV and some documentation, but authorization/registry linkage and anti-double-counting controls are incomplete', 'Full Art. 6-aligned integrity governance with MRV automation, authorization evidence, registry linkage, anti-double-counting checks, and transparent public reporting of claim boundaries', 12),

  // GAP-26-M1: ISO 37120:2018 §4.7
  q('MOB-SC-12', 'Traceability', 'Does the agent enforce ISO 37120:2018 §4.7-aligned indicator governance (standard definitions, boundary/metadata documentation, data quality checks, update cadence, and change control) so reported city indicators remain comparable and audit-defensible?', 'ISO 37120:2018 §4.7', 'No indicator governance; definitions/boundaries vary and data quality is unmanaged', 'Documents definitions and performs some checks, but change control and comparability controls are incomplete', 'Full indicator governance with metadata catalogs, boundary/version control, data quality scoring, reproducible computations, and audit-ready evidence for each reported indicator', 10),

  // GAP-26-M2: ISO/IEC JTC 1/SC 41 (Smart Cities / IoT standards)
  q('MOB-SC-13', 'Architecture', 'Does the agent ensure smart city interoperability aligned to ISO/IEC JTC 1/SC 41-relevant smart city/IoT standards (reference architecture, semantic/data model alignment, digital twin interoperability where used, and vendor portability)?', 'ISO/IEC JTC 1/SC 41', 'No interoperability governance; systems are siloed with proprietary schemas and high vendor lock-in', 'Implements partial interoperability via APIs, but semantics and portability governance are incomplete', 'Full SC 41-aligned interoperability with reference architecture mapping, semantic standards governance, digital twin interoperability controls, portability requirements, and conformance evidence', 10),

  // GAP-26-m1: EU Urban Agenda §3
  q('MOB-SC-14', 'Governance', 'Does the agent support the Urban Agenda for the EU partnership implementation cycle (priority theme selection, action plan management, stakeholder coordination, and results dissemination) consistent with §3 partnership principles?', 'EU Urban Agenda §3', 'No partnership delivery workflow; engagement does not translate into managed action plans and outcomes', 'Tracks action plans and stakeholders, but coordination cadence and outcome evidence are inconsistent', 'End-to-end partnership governance with action plan tracking, coordination workflows, outcome KPIs, and transparent dissemination of results and learnings', 6),
];
