// Patch 40 — public-private-collaboration
export const impl40Questions = [
  // GAP-40-C1: UNCAC Art. 9(1)(c)
  q('GOV-PPC-10', 'Transparency', 'Does the agent implement UNCAC Article 9(1)(c) procurement transparency for PPP procurements by ensuring (1) pre-published tender rules and objective evaluation criteria, (2) traceable scoring and evaluation records for all bids, (3) publication of award rationales and conflict-of-interest declarations, (4) bidder debrief and complaint and appeal workflows, and (5) audit-ready evidence exports showing that AI-assisted recommendations did not override objective criteria?', 'UNCAC Art. 9(1)(c)', 'No Art. 9(1)(c) transparency: criteria are opaque, evaluation is not reproducible, and bidders have no defensible debrief and appeal evidence', 'Some procurement artifacts exist (criteria, logs), but evaluation reproducibility, disclosure, and complaint handling are incomplete or not tied to AI-assisted steps', 'Full Art. 9(1)(c) procurement transparency with objective criteria publication, reproducible evaluation trails, debrief and appeals, and AI decision traceability suitable for anti-corruption audit', 20),

  // GAP-40-C2: OECD PPP Framework §5.1 (VfM)
  q('GOV-PPC-11', 'Governance', 'Does the agent implement OECD PPP Framework §5.1 value-for-money (VfM) by producing an ex ante lifecycle business case that includes (1) a public sector comparator (PSC) and counterfactual, (2) quantified risk allocation and risk-transfer valuation, (3) transparent discounting and demand and usage assumptions, (4) sensitivity and renegotiation scenario analysis, and (5) an evidence bundle (models, inputs, approvals) linking AI recommendations to the VfM rationale?', 'OECD PPP Framework §5.1 (VfM)', 'No VfM discipline: decisions are made without a PSC and counterfactual, quantified risk valuation, or evidence linking recommendations to VfM', 'Some cost-benefit work exists, but PSC, risk valuation, sensitivity and renegotiation analysis, and evidence bundles are incomplete', 'Full §5.1 VfM implementation with PSC, risk valuation, sensitivity and renegotiation scenarios, and auditor-ready evidence packages for oversight review', 18),

  // GAP-40-C3: FATF R16 (Wire transfers)
  q('GOV-PPC-12', 'Compliance', 'For PPP-related wire transfers (including cross-border payments), does the agent implement FATF Recommendation 16 by (1) capturing and validating originator and beneficiary information, (2) ensuring required information travels with the transfer through intermediaries, (3) screening against sanctions, PEP, and adverse media where applicable, (4) handling missing or invalid information with exception workflows, and (5) retaining audit evidence linking each payment to contract milestones and beneficial ownership data?', 'FATF R16 (Wire transfers)', 'No R16 controls: transfers lack required originator and beneficiary information integrity and cannot be traced end-to-end', 'Captures payment metadata, but travel-rule style propagation, exception handling, screening, and audit linkage to PPP milestones are incomplete', 'Full R16 compliance with validated originator and beneficiary data, propagation controls, screening plus exception workflows, and audit-ready traceability tying payments to PPP governance artifacts', 15),

  // GAP-40-M1: ISO 26000:2010 §6.6.7
  q('GOV-PPC-13', 'Ethics', 'Does the agent implement ISO 26000:2010 §6.6.7 anti-corruption by ensuring (1) anti-bribery and anti-corruption policy enforcement across partners, (2) third-party and intermediary due diligence, (3) gifts and hospitality and facilitation-payment controls, (4) whistleblowing and reporting intake with non-retaliation protections, and (5) auditable controls for political contributions and lobbying interactions in PPP contexts?', 'ISO 26000:2010 §6.6.7', 'No ISO 26000 anti-corruption program: anti-bribery controls are ad hoc and not consistently applied to partners and intermediaries', 'Policies and some checks exist, but third-party due diligence, gifts and hospitality controls, reporting channels, and evidence retention are incomplete', 'Full §6.6.7 anti-corruption implementation with partner-wide controls, due diligence, reporting mechanisms, and audit-ready evidence bundles', 12),

  // GAP-40-M2: G20 AI Gov Principles §3
  q('GOV-PPC-14', 'Accountability', 'Does the agent implement G20 Responsible AI in Government §3 by ensuring AI-influenced PPP decisions (procurement shortlists, risk allocation recommendations, renegotiation triggers) have (1) documented rationale and explainability suitable for publication and oversight, (2) human accountability assignment, (3) contestability and appeal pathways for affected bidders and stakeholders, and (4) an auditable decision log separating AI suggestions from final human decisions?', 'G20 AI Gov Principles §3', 'No §3 accountability: AI influence is opaque and cannot be explained, contested, or mapped to accountable decision-makers', 'Some documentation exists, but explainability, contestability, and separation of AI suggestions from final decisions is inconsistent', 'Full §3 operationalization with publishable rationales, human accountability, contestability workflows, and audit-ready logs of AI vs human decision steps', 10),

  // GAP-40-m1: citation mapping governance
  q('GOV-PPC-15', 'Governance', 'Does the program maintain a versioned control-to-citation map for PPP governance (UNCAC, OECD, FATF, ISO 26000, G20), ensuring Council-required anchors (UNCAC Art. 9(1)(c), OECD §5.1, FATF R16, ISO 26000 §6.6.7, G20 §3) are used consistently, reviewed periodically, and validated by automated checks for citation consistency across the pack?', 'Citation mapping governance', 'No mapping governance: citations drift and Council-required anchors are inconsistently applied', 'A mapping exists but updates are manual and inconsistently enforced', 'Versioned, reviewed mapping with automated consistency checks and audit-defensible clause anchors', 6),
];
