// Implementation patch for professional-practice — all gaps from audit
export const impl11Questions = [
  // GAP-11-C1: HITECH Act §13402; 45 CFR §164.404-408
  q('HLT-PP-12', 'Compliance', 'Does the agent implement breach notification governance aligned to HITECH Act §13402 and 45 CFR §164.404-408, including 60-day notifications, content requirements, individual vs media/HHS triggers, and breach log maintenance?', 'HITECH Act §13402; 45 CFR §164.404-408', 'No breach notification governance; deadlines/content/trigger thresholds are not tracked and evidence is not retained', 'Tracks breach events and deadlines, but notification content requirements, trigger thresholds, and evidence bundles are incomplete or manual', 'End-to-end §13402-aligned breach notification orchestration with deadline SLAs, notification content templates, threshold logic, evidence bundles (risk assessment + decision record), regulator-ready exports, and immutable breach log management', 12),
  // GAP-11-C2: HIPAA Privacy Rule 45 CFR §164.524
  q('HLT-PP-13', 'Compliance', 'Does the agent implement HIPAA right-of-access per 45 CFR §164.524, including 30-day fulfillment (with allowable extension handling), form and format (incl. electronic copies), third-party direction, identity verification, and fee limitations with tracking/audit evidence?', '45 CFR §164.524', 'No access-request workflow; requests are ad hoc and often exceed timelines or provide incomplete/incorrect formats', 'Basic request intake and tracking exists, but timeline management, third-party direction, format fulfillment, and fee controls are inconsistent', 'Closed-loop §164.524 workflow with request intake, identity verification, SLA tracking (30 days), extension notices, format negotiation, secure delivery, fee governance, and audit-ready evidence export', 15),
  // GAP-11-M1: AMA Code of Medical Ethics §1.1
  q('HLT-PP-14', 'Ethics', 'Does the agent support professional responsibility and patient-centered use of AI tools consistent with AMA Code of Medical Ethics §1.1 (e.g., clinician accountability for decisions/records, transparency about tool use where relevant, and safeguards prioritizing patient welfare over revenue optimization)?', 'AMA Code of Medical Ethics §1.1', 'No ethics governance; AI tooling incentives and outputs can override patient interests without accountability', 'Provides guidance and documentation prompts, but clinician responsibility, transparency, and conflict-of-interest controls are inconsistently enforced', 'Operational ethics governance with responsibility attestations, conflict-of-interest checks (billing optimization vs patient interest), disclosure templates where required, and audit-ready evidence of clinician oversight and patient-first safeguards', 10),
  // GAP-11-M2: State medical AI practice acts; state medical board AI guidance (varies by jurisdiction)
  q('HLT-PP-15', 'Governance', 'Does the agent enforce jurisdiction-aware medical practice constraints (state-by-state) for AI-assisted documentation/billing/communications—covering clinician supervision, required disclosures, prohibited delegation/unlicensed practice safeguards, and documentation of the responsible licensed professional?', 'State medical AI practice acts / medical board standards', 'No state-aware controls; workflows are uniform and can violate state practice standards', 'Supports some configuration by state, but coverage is incomplete and evidence of supervision/disclosure is inconsistent', 'Comprehensive jurisdictional compliance engine with state rules registry, workflow gating, supervision attestations, disclosure artifacts when required, and defensible audit trails mapping AI actions to licensed responsibility', 12),
  // GAP-11-M3: EU AI Act (2024/1689) Annex III §5; Articles 9-15
  q('HLT-PP-16', 'Compliance', 'If the agent is used in an Annex III §5 high-risk context, does it implement EU AI Act high-risk system obligations (Art. 9-15) including risk management, data governance, logging, transparency, and human oversight for practice-management automation?', 'EU AI Act Annex III §5; Arts. 9-15', 'No EU AI Act controls; classification is noted but obligations are not implemented or evidenced', 'Implements some controls (logging/oversight), but documentation and conformity-assessment evidence are incomplete', 'Full high-risk compliance with Art. 9-15 controls, technical documentation, monitoring, and audit-ready evidence bundles mapped to practice workflows', 10),
  // GAP-11-m1: 45 CFR §164.526; 45 CFR §164.528
  q('HLT-PP-17', 'Compliance', 'Does the agent support HIPAA individual rights operations beyond authorization, including amendment requests (§164.526) and accounting of disclosures (§164.528), with evidence capture and response SLAs?', '45 CFR §164.526; 45 CFR §164.528', 'No rights operations; requests are handled inconsistently and are not auditable', 'Tracks requests but does not enforce SLA/evidence completeness', 'End-to-end rights ops with standardized intake, SLA tracking, evidence bundles, and audit-ready exports', 8),
];
