// Implementation patch for farm-to-fork
// All new q() calls extracted from audit gaps
export const impl01Questions = [
  // GAP-01-C1: EU Regulation (EC) 178/2002 Art. 18(2)
  q('ENV-FF-10', 'Traceability', 'Does the agent maintain and rapidly produce `one step back / one step forward` traceability records (identify immediate supplier and immediate customer for each lot/batch) per EU General Food Law Regulation (EC) 178/2002 Article 18(2)?', 'EU Regulation (EC) 178/2002 Art. 18(2)', 'Cannot reliably identify immediate supplier/customer for lots; records are incomplete or not retrievable on request within operational timeframes', 'Maintains supplier and customer identities for lots/batches and can produce them on request, but with delays and gaps for intermediaries, rework, and split/merge operations', 'Real-time, audited one-step-back/one-step-forward traceability with automated lot genealogy (split/merge/rework), instant authority-ready exports, and continuous reconciliation against ERP/WMS events', 15),
  // GAP-01-C2: Codex CAC/RCP 1-1969 §3.2
  q('ENV-FF-11', 'Safety', 'Does the agent support HACCP hazard analysis and validated selection of control measures (including CCP/OPRP determination and validation) per Codex CAC/RCP 1-1969 §3.2?', 'Codex CAC/RCP 1-1969 §3.2', 'No systematic hazard analysis; hazards/control measures are implicit or undocumented and CCP/OPRP choices are not validated', 'Performs documented hazard analysis and proposes CCP/OPRP assignments with evidence references, but validation is periodic and requires substantial manual review', 'Continuously maintained hazard analysis with automated evidence ingestion (process changes, incidents, supplier changes), validated CCP/OPRP logic, and on-change revalidation workflows with signed approvals', 15),
  // GAP-01-M1: ISO 22000:2018 §8.5.4
  q('ENV-FF-12', 'Safety', 'Does the agent implement and verify operational control of identified food safety hazards (control measures, monitoring, corrections) per ISO 22000:2018 §8.5.4?', 'ISO 22000:2018 §8.5.4', 'Control measures are not implemented in workflows; monitoring/correction is ad-hoc and not linked to hazard analysis outputs', 'Implements control measures and monitors key parameters, but corrections and verification are not consistently linked to ISO 22000 evidence and change control', 'Closed-loop hazard control with automated monitoring, corrections, verification activities, and change-controlled linkage from hazard analysis to operational parameters and audit evidence', 12),
  // GAP-01-M2: EU Regulation (EU) 2018/848 Art. 28
  q('ENV-FF-13', 'Compliance', 'Does the agent manage organic operator certification and certificate validity (including scope changes and certificate availability) per EU Organic Regulation (EU) 2018/848 Article 28?', 'EU Organic Regulation (EU) 2018/848 Art. 28', 'No certification lifecycle tracking; certificate scope/validity is unknown or unmanaged', 'Tracks certificates and renewal dates and flags expired/invalid scope, but relies on manual updates and does not reconcile against control body records', 'Automated certificate lifecycle management with control-body reconciliation, scope change workflows, product-claim gating, and audit-ready evidence packs', 10),
  // GAP-01-M3: GLOBALG.A.P. IFA v6 AF.10
  q('ENV-FF-14', 'Ethics', 'Does the agent verify and maintain evidence for worker welfare controls on farms per GLOBALG.A.P. IFA v6 AF.10 (worker welfare)?', 'GLOBALG.A.P. IFA v6 AF.10', 'No worker welfare evidence; labor conditions are unmanaged by the agent', 'Tracks welfare-related checklists and incidents, but evidence is incomplete and not linked to remediation workflows', 'Continuous worker welfare assurance with auditable evidence capture, remediation tracking, grievance intake, and KPI reporting aligned to AF.10 controls', 10),
  // GAP-01-M4: EU Regulation (EU) 2023/1115 (EUDR) Art. 4(2) and Art. 5
  q('ENV-FF-15', 'Compliance', 'Does the agent operate an EUDR due diligence system and generate/retain due diligence statements for relevant products before placing them on the EU market per EUDR 2023/1115 Article 4(2) and Article 5?', 'EUDR 2023/1115 Art. 4(2), Art. 5', 'No due diligence statements are generated or retained; products are placed without required declarations', 'Generates due diligence statements for some products/suppliers, but coverage is incomplete and supporting evidence is not consistently retained', 'Automated due diligence statement generation and retention for all relevant products with evidence linkage (geolocation, risk assessment, mitigation) and audit-ready exports', 12),
  // GAP-01-m1: EU Regulation (EC) 178/2002 Art. 19(1)–(3)
  q('ENV-FF-16', 'Governance', 'Does the agent support rapid product withdrawal/recall decisioning and competent authority notification workflows per EU General Food Law Regulation (EC) 178/2002 Article 19(1)–(3)?', 'EU Regulation (EC) 178/2002 Art. 19(1)-(3)', 'No recall workflow; actions are improvised and authority notifications are inconsistent', 'Has documented recall steps and contact lists with semi-automated batch identification, but execution and notification are manual and slow', 'Automated recall orchestration with instant affected-lot identification, notification templating, authority-ready evidence bundles, and post-incident CAPA tracking', 8),
];
