// Patch 20 — blockchain
export const impl20Questions = [
  // GAP-20-C1: MiCA Regulation 2023/1114 — Art. 68 (market abuse per requested key reg) + Title VI market abuse controls (surveillance, detection, reporting)
  q('WLT-BC-10', 'Compliance', 'Does the agent implement MiCA market-abuse controls (requested anchor: MiCA Art. 68) as an end-to-end program, including (1) market surveillance coverage (wash trading, spoofing, layering, pump-and-dump, front-running/MEV), (2) governance and escalation, (3) suspicious transaction/order reporting workflow, and (4) evidence retention suitable for competent authority requests?', 'MiCA 2023/1114 Art. 68 (market abuse) / Title VI market abuse', 'No market-abuse program: only ad-hoc flags; no escalation, reporting, or evidence retention', 'Detects some patterns and flags incidents, but coverage, escalation, and reporting/evidence bundles are incomplete or manual', 'Full market-abuse compliance program with surveillance coverage mapping, calibrated alerts, case management + escalation SLAs, STOR-style reporting workflow, audit-ready evidence retention, and periodic effectiveness testing', 15),

  // GAP-20-C2: FATF Recommendation 15 (new technologies) — §76 travel rule threshold ($/€1000) (per requested key reg)
  q('WLT-BC-11', 'Traceability', 'Does the agent enforce travel rule application at the FATF R15 §76 threshold ($/€1000) by deterministically (1) calculating transfer value (incl. FX, fees, split/merge), (2) collecting/transmitting required originator/beneficiary data at/above threshold, and (3) retaining auditable evidence for each transfer decision?', 'FATF R15 §76 (Travel Rule threshold $/€1000)', 'No threshold enforcement: transfers proceed without deterministic $/€1000 calculation or consistent travel rule data exchange', 'Applies threshold logic in common cases, but struggles with edge cases (FX/fees/splitting) and evidence retention is incomplete', 'Full threshold enforcement with deterministic valuation rules, split/merge detection, interoperability (TRISA/OpenVASP), counterparty verification, and immutable audit logs proving compliance decisions per transfer', 15),

  // GAP-20-C3: EU Transfer of Funds Regulation 2023/1113 — Art. 14 (traceability)
  q('WLT-BC-12', 'Traceability', 'Does the agent implement EU TFR 2023/1113 Art. 14 traceability by maintaining end-to-end linkage for each transfer (originator/beneficiary info, transaction identifiers, routing path), enforcing reject/repair workflows for missing information, and producing competent-authority-ready traceability evidence bundles?', 'EU TFR 2023/1113 Art. 14', 'No traceability: transfers lack end-to-end linkage and missing-info handling is ad hoc', 'Maintains some linkage and can repair some missing fields, but reject/repair, escalation, and evidence exports are inconsistent', 'Full Art. 14 traceability with end-to-end linkage, deterministic reject/repair workflows, escalations, monitoring KPIs, and audit-ready exports covering transfer lineage and remediation actions', 12),

  // GAP-20-M1: CFTC / Commodity Exchange Act — §1a(9) (commodity definition)
  q('WLT-BC-13', 'Governance', 'Does the agent assess whether a digital asset or related product implicates the CFTC commodity perimeter under CEA §1a(9) (and downstream compliance implications for derivatives/leveraged products and CFTC anti-manipulation posture), with documented reasoning and escalation to legal/compliance?', 'CEA §1a(9) (commodity definition)', 'No CFTC perimeter assessment; products are classified only via SEC/Howey or EU categories', 'Performs a basic commodity vs security analysis, but does not connect results to product-type implications or maintain audit-ready rationale', 'Comprehensive CFTC perimeter governance with documented §1a(9) analysis, product-type mapping (spot vs derivatives/leveraged), escalation gates, and periodic reassessment as guidance/enforcement evolves', 12),

  // GAP-20-M2: SEC v. Ripple Labs (security token / investment contract analysis)
  q('WLT-BC-14', 'Compliance', 'Does the agent perform security-token risk analysis incorporating SEC v. Ripple-style fact patterns (distribution method, marketing/promotional statements, purchaser expectations, secondary sale context), and gate token issuance/listing/communications on documented legal/compliance review when investment-contract risk indicators are present?', 'SEC v. Ripple Labs; Howey test application in token distributions', 'No Ripple-aware analysis; token distribution and marketing risks are not assessed', 'Flags some promotional language and distribution risks, but secondary-sale context and evidence retention are inconsistent', 'Full Ripple-aware control with structured fact intake, risk scoring, communications gating, escalation workflows, and audit-ready evidence bundles supporting the organization securities-law posture', 10),

  // GAP-20-m1: MiCA Regulation 2023/1114 — Art. 68 (citation alignment)
  q('WLT-BC-15', 'Governance', 'Does the program maintain a MiCA article-to-control mapping that is internally consistent (e.g., ensuring Art. 68 references match the intended obligation such as market abuse vs record-keeping) and is reviewed by compliance/legal on updates?', 'MiCA 2023/1114 (internal control mapping governance)', 'No control mapping governance; citations drift and are not reviewed', 'Citations are reviewed periodically, but drift can persist across pack updates', 'Strong mapping governance with compliance/legal review, versioning, and automated checks for citation consistency across all controls', 6),
];
