// Patch 39 — citizen-services
export const impl39Questions = [
  // GAP-39-C1: law
  q('GOV-CS-10', 'Compliance', 'For all SDG-scoped procedures, does the agent ensure the full procedure is available fully online end-to-end (including identification/authentication, guidance, form completion, evidence submission, e-signature where applicable, fee/payment, status tracking, decision delivery, and appeal/redress initiation), with documented exceptions and accessibility-preserving alternative channels, per SDG Regulation (EU) 2018/1724 Article 2(2)?', 'EU SDG 2018/1724 Art. 2(2)', 'Procedure is not fully online: one or more mandatory steps require in-person/phone/mail workarounds or manual staff intervention, with no exception governance or evidence', 'Most steps are online, but identity/evidence/payment/decision delivery or redress steps still require offline actions or are inconsistently available across procedures', 'All SDG procedures are end-to-end fully online with exception governance, evidence of completion rates, cross-border accessibility checks, and auditable proof that offline steps are not mandatory except where legally justified', 15),

  // GAP-39-C2: law
  q('GOV-CS-11', 'Interoperability', 'Does the agent support eIDAS 2.0 cross-border use (per §6) by enabling (1) cross-border identification/authentication acceptance, (2) EUDI Wallet or equivalent credential presentation flows where applicable, (3) relying-party verification and attribute validation, (4) multilingual/cross-border error handling and support, and (5) evidence exports demonstrating successful cross-border transactions and interoperability testing?', 'eIDAS 2.0 §6 (cross-border)', 'No cross-border support: identity/credential flows work only for domestic users and fail for cross-border credentials or foreign-issued attributes', 'Some cross-border scenarios work, but coverage is incomplete, usability is poor, and there is limited evidence of interoperability testing and relying-party validation', 'Full cross-border readiness with interoperable identity/credential acceptance, relying-party verification, consistent UX across Member States, and audit-ready evidence of cross-border transactions and conformance testing', 18),

  // GAP-39-C3: law
  q('GOV-CS-12', 'Accessibility', 'Across all citizen-service user journeys (including AI-assisted decision notices, identity steps, uploads, and payments), does the agent ensure WCAG 2.1 SC 2.4.3 Focus Order is met (logical tab order, focus visibility where relevant, no focus traps, consistent focus management on dynamic updates), with automated regression tests and manual AT test evidence?', 'WCAG 2.1 SC 2.4.3', 'No focus-order control: keyboard navigation order is illogical, dynamic steps trap focus, or assistive technology users cannot complete procedures', 'Some pages meet focus order, but complex journeys (wizards/modals/dynamic forms) have inconsistent focus management and limited test evidence', 'End-to-end focus-order compliance across all journeys with automated checks, AT-supported manual test evidence, and change-control gates preventing regressions', 12),

  // GAP-39-M1: law
  q('GOV-CS-13', 'Accessibility', 'For web-based citizen services, does the agent meet Section 508 §1194.22 requirements (including text alternatives, keyboard access, non-interference with assistive tech, form label/field associations, timing control, and accessible documentation), and produce evidence bundles (test reports, exception logs, remediation tracking) suitable for procurement/audit?', 'Section 508 §1194.22', 'No 508 mapping: accessibility is asserted but not evidenced against §1194.22, with gaps in forms/keyboard/AT compatibility', 'Partial mapping: some criteria are met and tested, but gaps remain and evidence is not consistently retained or auditable', 'Full §1194.22 compliance with traceable criteria mapping, repeatable testing, remediation SLAs, and audit-ready evidence bundles', 10),
];
