// Patch 24 — specialized-education
export const impl24Questions = [
  // GAP-24-C1: Section 508 - 36 CFR Part 1194.21 (Software Applications and Operating Systems)
  q('EDU-SE-10', 'Compliance', 'Does the agent ensure Section 508 36 CFR Part 1194.21 software/application accessibility for specialized education creative tools (e.g., keyboard operability, focus indication, programmatic access to UI elements for assistive technology, no reliance on color alone, and accessible dialogs/controls) in addition to WCAG content conformance?', 'Section 508 - 36 CFR Part 1194.21', 'No 1194.21 coverage; creative tools may be unusable with keyboard or assistive technologies despite surface WCAG claims', 'Meets some 1194.21 expectations (keyboard and focus) but programmatic exposure/assistive technology testing and complex creative controls remain partially inaccessible', 'Full 1194.21 conformance with keyboard-only workflows, robust focus management, programmatic UI exposure for assistive technology, accessible complex controls (timelines/canvases), regression testing, and documented VPAT-ready evidence', 15),

  // GAP-24-C2: UNESCO Seoul Agenda: Goals for the Development of Arts Education (2010) - Goal 2
  q('EDU-SE-11', 'Governance', 'Does the agent support UNESCO Seoul Agenda 2010 Goal 2 by strengthening capacity for arts education (e.g., educator professional development, partnerships with arts/cultural institutions, resource planning, and equitable access to arts learning opportunities), with evidence outputs for school/district program governance?', 'UNESCO Seoul Agenda (2010) - Goal 2', 'No Goal 2 support; arts education capacity-building is not planned or evidenced, and programs depend on ad-hoc tooling rather than sustainable capability', 'Supports some professional development resources and partnership suggestions, but capacity-building is not measurable, resourcing is not tracked, and equity outcomes are not monitored', 'Full Goal 2 operationalization with professional development pathways, partnership MoU templates, resource/capability maturity tracking, equitable access monitoring, and audit-ready governance outputs showing capacity growth over time', 12),

  // GAP-24-C3: WHO International Classification of Functioning, Disability and Health (ICF) - b117 Intellectual functions
  q('EDU-SE-12', 'Safety', 'Does the agent implement ICF-informed educational supports by recognizing and accommodating learner functioning profiles, including WHO ICF b117 (intellectual functions), through adjustable cognitive load, memory supports, pacing controls, comprehension checks, and non-stigmatizing scaffolds with documented effectiveness monitoring?', 'WHO ICF - b117 Intellectual functions', 'No ICF support; the agent treats all learners as having uniform cognitive profiles and provides no measurable scaffolds or effectiveness monitoring', 'Provides some scaffolds (simplified language, hints) but does not map supports to ICF categories or measure accommodation effectiveness over time', 'Full ICF-informed support with b117-aligned scaffolding options, personalization controls, non-stigmatizing language, outcome monitoring for support effectiveness, and exportable accommodation evidence for educators', 12),

  // GAP-24-C4: ISTE Standards (2023) - 1b
  q('EDU-SE-13', 'Transparency', 'Does the agent operationalize ISTE Standards 2023 1b by supporting educator learning and networked practice (e.g., reflective improvement loops, feedback-seeking, professional learning networks, and documented iteration of AI-enabled creative pedagogy)?', 'ISTE Standards (2023) - 1b', 'No 1b support; educators lack structured learning/feedback loops and professional learning network support for AI creative pedagogy', 'Provides some guidance and resources, but feedback loops and evidence of professional learning/network participation are inconsistent or manual', 'Full 1b support with structured reflective practice, feedback collection, professional learning network participation workflows, measurable professional development outcomes, and evidence exports for instructional leadership', 10),

  // GAP-24-M1: Creative Commons license compliance (CC BY / BY-SA / BY-NC / BY-ND etc.)
  q('EDU-SE-14', 'Compliance', 'Does the agent enforce Creative Commons license compliance for educational remix and publishing by (1) generating correct attribution (TASL), (2) checking license compatibility (including ShareAlike), and (3) preventing prohibited uses under NC/ND constraints, with provenance tracking for all included assets?', 'Creative Commons license compliance', 'No Creative Commons compliance; the agent reuses/remixes assets without attribution, compatibility checks, or constraint enforcement', 'Generates attribution for some assets and flags obvious incompatibilities, but provenance is incomplete and NC/ND/SA enforcement is inconsistent', 'Full Creative Commons compliance with TASL attribution automation, license-compatibility graph checks, policy gating for NC/ND/SA, complete asset provenance, and exportable licensing manifests for OER publishing', 12),

  // GAP-24-m1: Jurisdictional scope gating (Section 508 vs EU accessibility regimes)
  q('EDU-SE-15', 'Governance', 'Does the program maintain a jurisdictional accessibility compliance matrix (e.g., U.S. Section 508/VPAT including 1194.21 vs EU accessibility directives), and gate rollout/procurement on completion of the correct evidence bundle for each deployment context?', 'Accessibility scope gating', 'No scope gating; accessibility claims are generic and evidence artifacts are missing or mismatched by jurisdiction', 'Maintains a manual matrix, but rollout gating and evidence retention are inconsistent across products and regions', 'Automated scope gating with jurisdiction mapping, VPAT/evidence bundle generation, and release checks that block deployment until locale-appropriate accessibility obligations are met', 6),
];
