// Implementation patch for ubiquity-to-utility
// All new q() calls extracted from audit gaps
export const impl05Questions = [
  // GAP-05-C1: NERC CIP-007-6 R1
  q('ENV-UU-10', 'Security', 'Does the agent enforce NERC CIP-007-6 R1 Ports and Services controls by maintaining baselines of enabled logical ports/services on each BES Cyber System, approving and documenting required services, and detecting/alerting on unauthorized enablement?', 'NERC CIP-007-6 R1', 'No ports/services baselines exist; services are enabled ad-hoc and unauthorized exposure is not detected', 'Maintains a baseline for most BES Cyber Systems and alerts on some deviations, but approvals/justifications and evidence retention are incomplete', 'Continuous CIP-007-6 R1 compliance with automated baselining, change approvals with documented business need, authenticated service inventories, drift detection, and audit-ready evidence bundles per BES Cyber System', 15),
  // GAP-05-C2: IEC 62351-8
  q('ENV-UU-11', 'Security', 'Does the agent implement role-based access control for power system operations per IEC 62351-8 (role definition, role assignment, access rights mapping, and authorization enforcement for control actions)?', 'IEC 62351-8', 'No OT RBAC model; control actions and configuration changes are not governed by standardized roles/rights', 'Defines roles and limits some actions, but role engineering is incomplete and authorization decisions are inconsistently enforced across OT interfaces', 'IEC 62351-8-aligned RBAC with formal role engineering, least-privilege rights mapping to IEC 61850/SCADA control points, strong authentication binding, break-glass governance, and complete authorization/audit evidence', 15),
  // GAP-05-M1: IEC 61850
  q('ENV-UU-12', 'Safety', 'Does the agent support secure interoperability with substation automation systems per IEC 61850 (including data modeling, MMS/GOOSE/Sampled Values messaging constraints, and configuration management via SCL) for grid monitoring and control use cases?', 'IEC 61850', 'No IEC 61850 interoperability; substation integration relies on proprietary mappings or manual operations', 'Supports partial IEC 61850 data models and messaging, but configurations and change control are manual and security constraints are inconsistently applied', 'Full IEC 61850 interoperability with validated SCL workflows, deterministic control messaging support, protection/control coordination safeguards, and standardized integration testing for substation automation', 12),
  // GAP-05-M2: EU RED III 2023/2413 Art. 15
  q('ENV-UU-13', 'Compliance', 'Does the agent manage renewable project permitting workflows per EU RED III 2023/2413 Article 15 (permit-granting process), including required documentation, timeline tracking, and coordination across competent authorities/one-stop shop procedures?', 'EU RED III 2023/2413 Art. 15', 'No permitting workflow support; permit documentation and timelines are unmanaged', 'Tracks key permit milestones and documents, but does not provide end-to-end timeline compliance monitoring or multi-authority coordination', 'End-to-end Art. 15 compliance with automated permit dossier generation, statutory timeline monitoring, authority coordination workflows, grid-connection dependency tracking, and audit-ready permitting evidence packs', 10),
  // GAP-05-M3: NERC CIP-013-1
  q('ENV-UU-14', 'Governance', 'Does the agent implement NERC CIP-013-1 supply chain risk management by enforcing procurement controls (including vendor risk evaluation, security requirements, and vendor incident/notification obligations) and maintaining evidence that the supply chain risk management plan is implemented?', 'NERC CIP-013-1', 'No CIP-013-1 procurement controls; vendor security requirements and notifications are not managed', 'Implements some procurement controls and tracks vendors, but requirements, notification obligations, and evidence retention are inconsistent', 'Full CIP-013-1 lifecycle with procurement control templates, vendor assurance and notification monitoring, software/firmware integrity verification, and continuously collected audit evidence mapped to CIP-013-1 requirements', 12),
  // GAP-05-m1: FERC Order 887
  q('ENV-UU-15', 'Safety', 'Does the agent continuously monitor inverter-based resource (IBR) model performance and trigger re-validation/updates (e.g., after control/firmware changes or event analysis) to maintain Order 887-aligned model accuracy for planning and operations studies?', 'FERC Order 887', 'No ongoing validation; IBR models are static and not updated after changes/events', 'Performs periodic validation, but triggers and evidence for updates after changes/events are inconsistent', 'Continuous Order 887-aligned model governance with automated drift detection, event-based re-validation triggers, controlled model updates, and evidence exports for planning coordinator/ISO submissions', 8),
];
