// Implementation patch for patient-lifecycle — all gaps from audit
export const impl09Questions = [
  // GAP-09-C1: 21 CFR §807.87 (FDA 510(k) content requirements)
  q('HLT-PL-12', 'Compliance', 'Does the agent support FDA 510(k) submission evidence completeness per 21 CFR §807.87, including intended use or indications alignment, device or software description, labeling controls, and performance testing documentation for patient-facing CDS or triage functions?', '21 CFR §807.87', 'No 510(k) evidence package; intended use or labeling or performance evidence is missing or inconsistent across agent features', 'Maintains partial 510(k) artifacts (device description, some performance evidence, draft labeling), but software documentation and testing traceability are incomplete or not audit-ready', 'Comprehensive 510(k) evidence orchestration with §807.87-aligned checklisting, software documentation (per FDA software guidance), performance or clinical evaluation evidence linkage, labeling change control, and submission-ready exports with gap reports', 15),

  // GAP-09-C2: ISO 14971:2019 §5.4
  q('HLT-PL-13', 'Safety', 'Does the agent perform and maintain a patient-workflow risk analysis per ISO 14971:2019 §5.4 (identify hazards, hazardous situations, foreseeable misuse, and sequences of events) for triage, CDS recommendations, care transitions, and patient communication?', 'ISO 14971:2019 §5.4', 'No formal risk analysis; hazards and failure sequences are undocumented or ad-hoc', 'Maintains a risk register for major hazards, but sequences of events or foreseeable misuse and linkage to risk controls is incomplete', 'Complete §5.4 risk analysis with sequence-of-events modeling (including data quality, automation bias, handoff failures), foreseeable misuse catalog, linkage to verified risk controls, and continuous updates from post-market signals', 15),

  // GAP-09-M1: Joint Commission NPSG.06.01.01
  q('HLT-PL-14', 'Safety', 'Does the agent implement medication reconciliation across transitions of care per Joint Commission NPSG.06.01.01 (obtain or compare medication lists, resolve discrepancies, and communicate the updated list to the next provider and the patient)?', 'Joint Commission NPSG.06.01.01', 'No reconciliation workflow; medication lists are incomplete, inconsistent, or not communicated at transitions', 'Performs basic list aggregation and discrepancy flagging, but reconciliation decisions or communications are manual and inconsistently documented', 'Closed-loop reconciliation with multi-source medication history (pharmacy claims, EHR, patient report), structured discrepancy resolution, documented clinician sign-off, patient-friendly discharge med list delivery, and audit-ready reconciliation evidence', 12),

  // GAP-09-M2: IEC 62304:2006 §5.2
  q('HLT-PL-15', 'Traceability', 'Does the agent support software requirements analysis and requirements traceability for safety-related functions per IEC 62304:2006 §5.2 (including linkage to risk controls and verification evidence)?', 'IEC 62304:2006 §5.2', 'No software requirements; behavior is implicit and tests do not trace to safety requirements', 'Maintains partial requirements and some trace links to tests, but risk-control linkage and change impact analysis are incomplete', 'Full §5.2 compliance with safety-class-driven requirements rigor, bidirectional traceability (hazard → requirement → implementation → verification), change impact analysis, and release gating on trace completeness', 12),

  // GAP-09-M3: EU MDR 2017/745 Annex I §1
  q('HLT-PL-16', 'Safety', 'Does the agent demonstrate EU MDR 2017 or 745 Annex I §1 alignment by documenting risk-benefit, state of the art safety measures, and risk reduction as far as possible for patient-lifecycle automation (triage or CDS or coordination)?', 'EU MDR 2017/745 Annex I §1', 'No GSPR evidence; risk-benefit and state-of-the-art rationale are absent for automated clinical functions', 'Documents high-level risk-benefit and some safety measures, but does not maintain state-of-the-art justification or residual risk acceptability rationale', 'Comprehensive GSPR evidence pack with state-of-the-art benchmarked controls, quantified risk-benefit support, residual risk evaluation or acceptability rationale, and continuous update from vigilance and real-world performance data', 10),

  // GAP-09-m1: Joint Commission NPSGs (terminology alignment)
  q('HLT-PL-17', 'Governance', 'Does the agent maintain an accreditor crosswalk mapping JCI standards to Joint Commission NPSG controls (including NPSG.06.01.01) with evidence pointers and responsibility assignments?', 'Joint Commission NPSG crosswalk expectations', 'No crosswalk; teams cannot map implemented controls to NPSGs or JCI requirements', 'Maintains a partial mapping spreadsheet, but it is not kept current with changes and lacks evidence pointers', 'Automated control crosswalk with versioned mappings, evidence pointers (policies, logs, test reports), and change alerts when accreditor standards update', 6),
];
