// Patch 29 — virtual-infrastructure
export const impl29Questions = [
  // GAP-29-C1: law
  q('MOB-VI-10', 'Access Control', 'Does the agent implement FedRAMP Rev. 5 / NIST SP 800-53 Rev.5 AC-2 Account Management, including (1) documented account types and approval workflows, (2) privileged account lifecycle controls, (3) external/third-party account governance, (4) automated deprovisioning/disablement on role change/termination, (5) periodic account/access reviews with reconciliation, and (6) immutable audit evidence for all account events?', 'FedRAMP Rev. 5 AC-2', 'No AC-2 controls: accounts are created/managed ad hoc; privileged/external accounts are not governed; deprovisioning and reviews are inconsistent; audit evidence is missing', 'Partial AC-2: basic provisioning and some reviews exist, but privileged/external account governance, reconciliation, and evidence completeness are inconsistent', 'Full AC-2 implementation with lifecycle automation, privileged/external account governance, periodic reconciliation, exception handling, and FedRAMP-audit-ready evidence bundles for assessors', 15),

  // GAP-29-C2: law
  q('MOB-VI-11', 'Governance', 'Does the agent implement ISO/IEC 27001:2022 Annex A control A.5.23 by governing the secure use of cloud services, including (1) cloud service selection and onboarding criteria, (2) shared responsibility matrix definition and maintenance, (3) required contractual security clauses and audit rights, (4) configuration baseline/hardening governance, (5) monitoring of cloud service use and drift, and (6) evidence linking cloud controls to the Statement of Applicability?', 'ISO/IEC 27001:2022 A.5.23', 'No cloud-use governance: cloud services are adopted without defined security requirements, shared responsibility, baselines, or evidence mapping', 'Some governance exists (policies/baselines), but shared responsibility, contract controls, and SoA/evidence mapping are incomplete or inconsistent', 'Full A.5.23 implementation with controlled onboarding, shared responsibility governance, contractual control enforcement, baseline/drift monitoring, and auditor-ready evidence mapped to SoA', 12),

  // GAP-29-C3: law
  q('MOB-VI-12', 'Interoperability', 'Does the agent implement EU Data Act Art. 25 cloud switching and exit readiness, including (1) provider-to-provider switching plan and tested runbooks, (2) functional equivalence mapping for critical services, (3) data/application export formats and portability tooling, (4) exit assistance obligations and evidence retention, (5) switching timelines, cost/charge constraints governance, and (6) post-exit data deletion/verification workflows?', 'EU Data Act 2023/2854 Art. 25', 'No switching readiness: no exit plan, no functional equivalence mapping, no tested migration runbooks, and no audit-ready evidence of switching support', 'Partial readiness: some export/migration tooling exists, but equivalence mapping, timelines/cost governance, and evidence are incomplete', 'Full Art. 25 compliance with tested switching runbooks, equivalence mapping, portability tooling, contractual assistance governance, timeline/cost controls, and regulator/auditor-ready evidence', 12),

  // GAP-29-C4: law
  q('MOB-VI-13', 'Governance', 'Does the agent implement NIS2 Art. 21 by maintaining an auditable mapping and evidence for each of the 10 measure categories (a)-(j), including risk analysis/policies, incident handling, business continuity/crisis management, supply chain security, secure acquisition/development/maintenance, effectiveness testing/auditing, cryptography, HR/access/asset governance, MFA/secure communications, and cybersecurity training, with reporting readiness for management accountability?', 'EU NIS2 2022/2555 Art. 21(2)(a)-(j)', 'No category coverage evidence: NIS2 is treated as a generic label without category mapping or audit-ready evidence', 'Some categories are implemented, but mapping/evidence is incomplete and several categories are weak or untested', 'Full Art. 21 implementation with category-by-category controls, evidence packs, effectiveness testing, and management reporting for compliance and incident scrutiny', 12),

  // GAP-29-m1: law
  q('MOB-VI-14', 'Governance', 'Does the program maintain a versioned regulatory mapping for the pack (FedRAMP Rev.5, NIS2 2022/2555, ISO 27001:2022, EU Data Act 2023/2854) with periodic review so legal/control citations and evidence expectations remain audit-defensible over time?', 'Regulatory mapping governance', 'No mapping governance: citations drift and evidence cannot be reliably mapped to specific controls/articles', 'Mapping exists but updates are manual and can lag regulatory changes', 'Versioned regulatory mapping with review workflow and automated checks for citation consistency and evidence linkage across the pack', 6),
];
