// Patch 27 — sustainable-ports
export const impl27Questions = [
  // GAP-27-C1: MARPOL Annex VI Reg. 14 (SOx control; 0.10% m/m sulfur in ECAs)
  q('MOB-SP-10', 'Compliance', 'Does the agent enforce and evidence MARPOL Annex VI Reg. 14 SOx compliance, including (1) 0.10% m/m sulfur limit applicability in ECAs, (2) validation of bunker delivery notes (BDNs) and fuel sampling data, (3) fuel changeover procedure + log verification for ECA entry/exit, and (4) EGCS/scrubber equivalency monitoring and exception handling where applicable?', 'MARPOL Annex VI Reg. 14 (ECA 0.10% sulfur limit)', 'No ECA-specific SOx controls; evidence (BDNs/changeover logs/EGCS data) is missing and compliance relies on manual assertions', 'Tracks fuel sulfur and retains some evidence, but ECA boundary logic, changeover verification, and PSC-ready evidence bundles are incomplete or inconsistent', 'Full Reg. 14 compliance automation with ECA geofencing, changeover verification, BDN + sample validation, EGCS equivalency monitoring, noncompliance detection/escalation, and PSC-ready evidence packs per voyage/call', 15),

  // GAP-27-C2: ISPS Code Part A §9.2
  q('MOB-SP-11', 'Security', 'Does the agent validate ship–port interface security by checking that the ship security plan (SSP) content and measures meet ISPS Code Part A §9.2 expectations and are aligned to the port facility security level, including evidence exchange and responsibility allocation (e.g., Declaration of Security where used)?', 'ISPS Code Part A §9.2', 'No SSP validation; ship–port interface security relies on ad-hoc checks and undocumented assumptions', 'Performs basic SSP document checks and some alignment to facility security level, but does not verify §9.2 content coverage or maintain audit-ready evidence of interface responsibilities', 'Full ship–port interface assurance with §9.2 SSP content validation, security-level alignment checks, DoS workflow support, evidence retention, and exception escalation tied to access control and cargo operations', 15),

  // GAP-27-C3: IMDG Code §1.3 (Training)
  q('MOB-SP-12', 'Safety', 'Does the agent enforce IMDG Code §1.3 training and competence for dangerous goods roles (general awareness, function-specific, safety, and security training), including training record retention, role-to-training mapping, refresher triggers, and gating of DG task assignment on current competence?', 'IMDG Code §1.3', 'No DG training governance; staff competence is not verified and records are missing or outdated', 'Tracks DG training records and schedules refreshers, but role mapping, task gating, and evidence completeness are inconsistent', 'Full §1.3 compliance with role-based competence matrices, automated refresher triggers, task gating, immutable training evidence, and audit-ready reports aligned to IMDG training elements', 12),

  // GAP-27-M1: ISO 28000:2022 §6.1
  q('MOB-SP-13', 'Governance', 'Does the agent implement ISO 28000:2022 §6.1 by maintaining a structured supply chain security risk and opportunity register, defining risk treatment plans and acceptance criteria, linking treatments to measurable security objectives, and reviewing updates based on changes/incidents?', 'ISO 28000:2022 §6.1', 'No §6.1 planning; risks/opportunities are informal and security controls are not linked to objectives or treatment plans', 'Maintains a risk register and some treatment actions, but methodology, acceptance criteria, and objective linkage are incomplete or inconsistently evidenced', 'Full §6.1 implementation with defined methodology, treatment planning + tracking, objective/KPI linkage, change-triggered review, and audit-ready evidence for continual improvement', 12),

  // GAP-27-M2: C-TPAT Minimum Security Criteria §1 (Business Partner Requirements)
  q('MOB-SP-14', 'Security', 'Does the agent operationalize C-TPAT Minimum Security Criteria §1 (Business Partner Requirements) by vetting partners, maintaining written security expectations/agreements, monitoring partner compliance (audits/attestations), and enforcing remediation/escalation when partner controls fail?', 'C-TPAT MSC §1', 'No partner security governance; partners are onboarded/used without defined security expectations or monitoring', 'Has partner screening and periodic attestations, but monitoring depth, remediation tracking, and decision gating are inconsistent', 'Full C-TPAT §1 governance with risk-based partner segmentation, contractual control requirements, continuous monitoring, remediation SLAs, and operational gating for noncompliant partners', 10),
];
