// Implementation patch for clinical-lifecycle — all gaps from audit
export const impl10Questions = [
  // GAP-10-C1: FDA 21 CFR §820.30(f) (Design verification)
  q('HLT-CL-12', 'Traceability', 'Does the agent manage and evidence design verification per FDA 21 CFR §820.30(f), including verification planning, objective evidence that design outputs meet design inputs, acceptance criteria, and bidirectional traceability (input → output → verification results)?', 'FDA 21 CFR §820.30(f)', 'No design verification; outputs are not verified against inputs and evidence is missing or ad hoc', 'Maintains some verification tests and trace links, but coverage is incomplete and acceptance criteria are inconsistently documented', 'Full design verification governance with protocol templates, defined acceptance criteria, traceability completeness checks, automated gap reporting, and release gating on verification evidence', 15),
  // GAP-10-C2: IEC 62366-1:2015 §5.7 (Usability evaluation)
  q('HLT-CL-13', 'Safety', 'Does the agent support usability engineering per IEC 62366-1:2015 §5.7 by planning and capturing summative usability evaluation evidence for safety-critical clinical workflows (including use-related risk scenarios, representative users, and documented residual use-related risk)?', 'IEC 62366-1:2015 §5.7', 'No usability evaluation; UI/workflow changes ship without summative evidence for safety-critical tasks', 'Performs some usability testing, but it is not tied to use-related risk controls and evidence is incomplete for regulated review', 'Full usability evaluation lifecycle with use-related risk scenarios, representative-user studies, traceability to risk controls, documented residual risk acceptance, and audit-ready reports', 15),
  // GAP-10-C3: EU MDR 2017/745 Art. 10(9) (Manufacturer QMS)
  q('HLT-CL-14', 'Governance', 'Does the agent implement and evidence EU MDR 2017/745 Article 10(9) manufacturer QMS requirements, including integrated procedures for risk management, clinical evaluation, PMS/vigilance, control of nonconforming outputs, CAPA, and change control (with role/accountability assignments)?', 'EU MDR 2017/745 Art. 10(9)', 'No MDR QMS; controls are scattered and not governed by an audit-ready QMS framework', 'Has documented procedures for some Art. 10(9) elements, but integration, ownership, and evidence linkage are incomplete', 'Comprehensive MDR QMS orchestration with integrated procedures, evidence pointers per control, automated audit pack generation, and continuous monitoring of QMS effectiveness', 15),
  // GAP-10-M1: ISO 13485:2016 §7.3.3 (Design and development inputs)
  q('HLT-CL-15', 'Traceability', 'Does the agent manage design and development inputs per ISO 13485:2016 §7.3.3, ensuring inputs are complete/unambiguous, include regulatory + safety + usability requirements, are reviewed/approved, and are traced through outputs, verification, and validation?', 'ISO 13485:2016 §7.3.3', 'No controlled design inputs; requirements are informal and not approved or traceable', 'Maintains requirements, but completeness/conflict checks and approval/traceability are inconsistent', 'Full design input control with structured requirements, review/approval workflow, conflict detection, regulatory/safety/usability coverage checks, and bidirectional traceability to verification/validation evidence', 12),
  // GAP-10-M2: FDA 21 CFR §820.70 (Production and process controls)
  q('HLT-CL-16', 'Governance', 'Does the agent enforce production and process controls per FDA 21 CFR §820.70 for clinical AI systems (controlled build/release processes, configuration/environment controls, process validation where applicable, and production monitoring with deviation handling)?', 'FDA 21 CFR §820.70', 'No controlled production processes; releases and configuration changes are manual and not validated or monitored', 'Uses CI/CD and basic change controls, but environment/configuration drift and release validation evidence are incomplete', 'Fully controlled production controls with validated pipelines, configuration baselines, segregation of duties, monitored production KPIs, deviation/CAPA linkage, and audit-ready release evidence', 12),
];
