// Implementation patch for wellness-management
// All new q() calls extracted from audit gaps
export const impl08Questions = [
  // GAP-08-C1: [GDPR Art. 22(1) (and associated safeguard expectations in Art. 22(3), Arts. 13–15)]
  q('HLT-WM-12', 'Compliance', 'Does the agent prevent solely automated decisions with legal or similarly significant effects based on wellness/health data by implementing GDPR Art. 22(1) safeguards (human review, ability to contest, and meaningful information about the logic for any consequential scoring/eligibility decisions)?', 'GDPR Art. 22(1) (and safeguards per Art. 22(3), Arts. 13–15)', 'Wellness scores/flags are used to automatically make consequential decisions (eligibility, benefits, access) with no human review or contest mechanism', 'Provides human review on request and basic explanation, but consequential decisions can still be executed by default from automated scoring and contest timelines are unclear', 'Default human-in-the-loop for consequential decisions, clear non-solely-automated routing, robust contest workflow with SLAs, meaningful explanation of key factors, and documented assessment of `similarly significant effect` for each decision pathway', 15),
  // GAP-08-C2: [FTC Health Breach Notification Rule, 16 CFR Part 318; §318.6]
  q('HLT-WM-13', 'Compliance', 'Does the agent support FTC Health Breach Notification Rule compliance by detecting `breaches of security` involving identifiable health information and executing end-to-end notification workflows (timely notice, required contents, and recipient-specific routing) per 16 CFR Part 318, including §318.6?', 'FTC HBNR 16 CFR Part 318; §318.6', 'No breach-notice workflow; incidents are handled ad hoc and required notices are missed or incomplete', 'Has an incident playbook and can generate draft notices, but cannot reliably determine HBNR applicability, track timing, or ensure required notice contents and delivery', 'Automated HBNR applicability triage, evidence-backed incident timeline, notice templating meeting §318.6 content requirements, delivery tracking, and audit-ready logs of all notifications and determinations', 12),
  // GAP-08-M1: [ADA Title III, 42 U.S.C. §12182]
  q('HLT-WM-14', 'Ethics', 'Does the agent ensure non-discriminatory access to wellness services for users with disabilities by meeting ADA Title III §12182 obligations (reasonable modifications, effective communication/auxiliary aids, and accessible digital interaction flows)?', 'ADA Title III, 42 U.S.C. §12182', 'Core flows are not accessible (e.g., screen-reader issues, inaccessible forms), and no accommodation pathway exists', 'Meets baseline accessibility checks and provides some accommodations, but coverage is inconsistent (chat, charts, videos, consent flows) and no systematic regression testing exists', 'End-to-end accessible wellness experience with verified accessibility across all critical flows (onboarding/consent, crisis escalation, dashboards), documented accommodation policy, accessibility regression testing, and effective-communication support for assistive technologies', 10),
  // GAP-08-M2: [EU AI Act — High-risk AI obligations for Annex III systems (Annex III §5)]
  q('HLT-WM-15', 'Governance', 'For wellness systems classified as high-risk under EU AI Act Annex III §5, does the agent implement provider-side high-risk controls (risk management, data governance, logging, human oversight, and QMS/conformity assessment evidence) appropriate to Annex III §5 use cases?', 'EU AI Act Annex III §5 (high-risk) — provider obligations', 'No high-risk AI lifecycle controls; limited documentation, weak logging, and no defined human oversight for consequential outputs', 'Maintains partial documentation and some logging, but risk management and data governance are incomplete and conformity evidence is fragmented', 'Full high-risk lifecycle controls with documented risk management, dataset governance, technical documentation, event logging, human oversight controls, and audit-ready evidence supporting conformity assessment for Annex III §5 deployments', 12),
  // GAP-08-M3: [ISO 13485:2016 §7.3 (Design and development)]
  q('HLT-WM-16', 'Safety', 'If the wellness agent includes medical-like intervention selection/monitoring features, does the development and change process follow ISO 13485:2016 §7.3 design & development controls (planning, inputs, outputs, review, verification, validation, transfer, and change control)?', 'ISO 13485:2016 §7.3', 'No design controls; requirements, V&V, and change impacts are undocumented or inconsistent', 'Has documented requirements and some testing, but design reviews, validation evidence, and change-control traceability are incomplete', 'Full ISO 13485-aligned design controls with traceable requirements, design reviews, verification/validation protocols, release gates, design transfer controls, and design-change impact analysis with auditable records', 10),
  // GAP-08-m1: [ADA Title I vs Title III (scope clarity); 42 U.S.C. §12182 for public accommodations]
  q('HLT-WM-17', 'Governance', 'Does the program explicitly scope ADA obligations across both workplace wellness (Title I) and consumer/public-accommodation delivery (Title III §12182), with controls and evidence mapped to each deployment context?', 'ADA Title III §12182 (scope clarity) + ADA Title I context', 'No scope mapping; ADA controls are assumed to be satisfied by workplace-only privacy separation', 'Documents deployment contexts and some mapped controls, but evidence is incomplete and gaps are handled reactively', 'Explicit context-based control mapping with evidence for each deployment model (employer-sponsored vs direct-to-consumer), periodic reviews, and documented accountability for accommodations/accessibility', 6),
];
