// Implementation patch for clinical-trials — all gaps from audit
export const impl14Questions = [
  // GAP-14-C1: ICH E6(R2) §5.18.4(e) (Monitor responsibilities; electronic monitoring)
  q('HLT-CT-12', 'Governance', 'Does the agent support electronic/remote monitoring per ICH E6(R2) §5.18.4(e) by enforcing controlled monitor access to electronic systems (eSource/EDC/eTMF), logging monitor activities/findings, supporting documented SDV/SDR approaches, and ensuring follow-up actions are tracked to closure?', 'ICH E6(R2) §5.18.4(e)', 'No electronic monitoring controls; monitor access is unmanaged and monitoring evidence/follow-up is incomplete or not audit-ready', 'Implements basic remote monitoring access and findings tracking, but activity logging, SDV approach documentation, and closure evidence are inconsistent', 'Full electronic monitoring governance with role-based monitor access, immutable activity logs, SDV/SDR plan management, centralized + on-site monitoring evidence consolidation, CAPA linkage, and inspection-ready monitoring reports', 15),

  // GAP-14-C2: EU CTR 536/2014 Art. 37 (Safety reporting)
  q('HLT-CT-13', 'Safety', 'Does the agent implement EU CTR 536/2014 Article 37 safety reporting workflows (including SUSAR reporting and periodic/annual safety reporting), with jurisdiction-aware timelines, submission readiness tracking, and reconciliation against case processing to ensure completeness and timeliness?', 'EU CTR 536/2014 Art. 37', 'No EU CTR safety reporting; SUSAR/periodic safety reporting is manual, inconsistent, or not traceable to source safety cases', 'Tracks EU safety cases and reporting deadlines, but reconciliation, completeness checks, and submission evidence are incomplete', 'Full EU CTR safety reporting automation with SUSAR + periodic safety report orchestration, case/report reconciliation, submission evidence retention, audit trails, and continuous compliance monitoring across member states', 15),

  // GAP-14-C3: FDA 21 CFR §312.62 (Investigator recordkeeping and record retention)
  q('HLT-CT-14', 'Compliance', 'Does the agent enforce investigator recordkeeping and retention per FDA 21 CFR §312.62, including complete case histories, drug disposition records, and retention scheduling based on regulatory triggers (e.g., 2 years after marketing application approval or discontinuation/withdrawal notice)?', 'FDA 21 CFR §312.62', 'No retention governance; site records are incomplete or retention periods are not tracked/enforced', 'Maintains records and basic retention policies, but trigger-based retention scheduling, completeness checks, and retrieval readiness are inconsistent', 'Full §312.62 compliance with record completeness checks, trigger-based retention automation, defensible destruction holds, rapid retrieval/export for inspection, and cross-system linkage (EDC/eSource/pharmacy/IRB) with audit logs', 15),

  // GAP-14-M1: Declaration of Helsinki §23 (Research ethics committee review/approval)
  q('HLT-CT-15', 'Ethics', 'Does the agent implement research ethics committee governance consistent with Declaration of Helsinki §23 by ensuring protocol/materials are submitted for independent ethics review and approval prior to trial start, tracking conditions/approvals, and preventing study activities prior to documented approval?', 'Declaration of Helsinki §23', 'No Helsinki governance; approvals are not reliably tracked and study activities can proceed without confirmed independent ethics approval', 'Tracks ethics approvals, but enforcement (no-start gating) and condition/continuing oversight tracking are inconsistent', 'Full Helsinki-aligned ethics governance with no-start/no-change gates, approval condition tracking, continuing oversight reminders, deviation/escalation workflows, and audit-ready ethics committee evidence exports', 12),

  // GAP-14-M2: GDPR Art. 9(2)(j) (Scientific research) + Art. 89(1) safeguards
  q('HLT-CT-16', 'Compliance', 'Does the agent implement GDPR special-category health data processing for scientific research under Art. 9(2)(j), including Art. 89 safeguards (pseudonymisation where possible, purpose limitation, data minimization, access controls, and retention governance) for clinical trial datasets and operational systems?', 'GDPR Art. 9(2)(j); Art. 89(1)', 'No GDPR research basis/safeguards; health data is processed without a documented Art. 9(2)(j) basis or consistent safeguards', 'Documents a research basis and applies some safeguards (e.g., pseudonyms), but minimization, retention, and access governance are inconsistent across systems/vendors', 'Full GDPR research governance with documented lawful basis, safeguards-by-default across EDC/eSource/analytics, automated retention + access reviews, DPIA linkage, and audit-ready evidence for supervisory authorities and partners', 12),
];
