// Patch 19 — circular-economy
export const impl19Questions = [
  // GAP-19-C1: SEC Climate Rules
  q('WLT-CE-10', 'Compliance', 'Does the agent support SEC Climate Rules greenhouse gas emissions disclosure per Regulation S-K 17 CFR §229.1502, including (1) defined organizational and operational boundaries, (2) consistent methodology and calculation controls, (3) disclosure controls and procedures and audit trail, and (4) ability to generate filing-ready disclosures with documented assumptions and change history?', 'SEC Climate Rules — 17 CFR §229.1502', 'No SEC climate disclosure readiness: boundaries and methodologies are undefined or inconsistent and disclosures cannot be reproduced with evidence', 'Has documented methodology and can generate emissions outputs, but boundary decisions, change control, and disclosure controls are incomplete or not audit-ready', 'Full §229.1502 readiness with boundary governance, methodology change control, disclosure controls and procedures, evidence retention, and filing-ready outputs aligned to SEC expectations', 15),

  // GAP-19-C2: ESRS E1 Scope 3
  q('WLT-CE-11', 'Compliance', 'Does the agent implement CSRD-aligned ESRS E1 value-chain (Scope 3) governance, including (1) coverage across relevant Scope 3 categories, (2) boundary and consolidation approach documentation, (3) estimation hierarchy and data quality scoring, and (4) assurance-ready evidence bundles and change logs for reported Scope 3 metrics?', 'EU CSRD 2022/2464; ESRS E1 (Scope 3/value-chain)', 'No ESRS E1 Scope 3 governance: categories are not mapped, boundaries are unclear, and reported figures are not reproducible with evidence', 'Maps major categories and produces estimates, but data quality/coverage controls and assurance evidence are incomplete', 'Full ESRS E1 Scope 3 governance with category mapping, boundary documentation, estimation controls, data quality scoring, and auditor-ready evidence packs with change history', 12),

  // GAP-19-M1: EU Taxonomy Art 8
  q('WLT-CE-12', 'Transparency', 'Does the agent compute and disclose EU Taxonomy Article 8 KPIs (taxonomy-eligible vs taxonomy-aligned turnover, CapEx, OpEx) with traceable mappings from financial line items to underlying economic activities, including evidence for eligibility/alignment and reconciliation to financial statements?', 'EU Taxonomy 2020/852 Art. 8', 'No Art. 8 KPI disclosures: taxonomy KPIs are not computed or cannot be reconciled to financial statements and activity evidence', 'Computes taxonomy KPIs for some activities, but mappings, reconciliations, and evidence are incomplete', 'Full Art. 8 KPI disclosure readiness with traceable mappings, reconciliation to financial statements, evidence links, and repeatable disclosure-generation workflows', 12),

  // GAP-19-M2: ISO 14040 14044
  q('WLT-CE-13', 'Traceability', 'Does the agent ensure lifecycle assessment (LCA) governance aligned to ISO 14040 and 14044, including (1) explicit goal and scope definition and functional unit, (2) boundary, allocation, and cut-off rules, (3) data quality requirements, and (4) critical review triggers and evidence retention when LCA supports external claims?', 'ISO 14040:2006; ISO 14044:2006', 'No LCA governance: LCAs are ad-hoc with unclear scope and boundaries and no critical review readiness for external claims', 'Maintains basic LCA templates and assumptions, but allocation and boundary discipline and critical review readiness are inconsistent', 'Full ISO 14040 and 14044 governance with goal and scope controls, data quality rules, critical review workflow triggers, and auditable evidence bundles for claim substantiation', 10),

  // GAP-19-M3: Ellen MacArthur CE100
  q('WLT-CE-14', 'Governance', 'Does the agent support programmatic circular economy governance aligned to Ellen MacArthur Foundation CE100 practices, including defined circular targets/KPIs, periodic progress reporting, evidence of participation/benchmarking (or equivalent peer learning), and decision gates that tie investment choices to verified circular outcomes?', 'Ellen MacArthur Foundation CE100', 'No programmatic circular governance: circular targets are absent or not linked to decisions and progress is not evidenced', 'Has circular targets and reports progress, but benchmarking/learning loops and decision gating are incomplete', 'Full CE100-style governance with targets/KPIs, periodic reporting, benchmarking/peer-learning evidence, and investment decision gates tied to verified circular outcomes', 8),

  // GAP-19-m1: ESRS scope map
  q('WLT-CE-15', 'Governance', 'Does the program maintain an explicit ESRS scope map for CSRD reporting (which ESRS standards/data points are in scope for the entity/product), and gate reporting outputs on completion of the required ESRS set (including explicit treatment of Scope 3/value-chain disclosures)?', 'EU CSRD 2022/2464; ESRS scope governance', 'No ESRS scope map: reporting scope is implicit and outputs vary across teams and periods', 'Maintains a policy memo describing scope, but gating and evidence retention are inconsistent across teams and releases', 'Formal ESRS scope map with reporting gates, evidence checklists, and change control so scope changes are documented and audit-ready', 6),
];
