// Patch 38 — petition-to-law
export const impl38Questions = [
  // GAP-38-C1: law
  q('GOV-PL-10', 'Open Data', 'Does the agent implement EU Open Data Directive (EU) 2019/1024 Article 5 by ensuring legislative/petition documents and datasets are made available (1) in machine-readable formats, (2) with complete metadata, (3) with bulk download and where data is dynamic API access, (4) with publication and update SLAs, and (5) with evidence artifacts (metadata schema, API docs, change logs, uptime metrics) to demonstrate ongoing compliance?', 'EU Open Data Directive (EU) 2019/1024 Art. 5', 'No Art. 5 implementation: data is not machine-readable, lacks metadata, and provides no API or bulk access for reuse', 'Some open formats/feeds exist, but metadata, API or bulk access, update SLAs, and compliance evidence are incomplete', 'Full Art. 5 compliance with machine-readable releases, metadata completeness, API and bulk access for dynamic datasets, publication and update SLAs, and audit-ready evidence artifacts', 18),

  // GAP-38-C2: law
  q('GOV-PL-11', 'Interoperability', 'For any geospatial legislative datasets (affected regions, constituency maps, project locations, zoning overlays), does the agent implement INSPIRE Directive 2007/2/EC Article 7 interoperability by aligning datasets and services to INSPIRE implementing rules (harmonised data models, schemas, code lists), validating conformance, and publishing conformance reports and transformation pipelines as evidence?', 'EU INSPIRE 2007/2/EC Art. 7', 'No INSPIRE interoperability: geospatial legislative data is ad hoc and cannot be harmonised or validated against INSPIRE implementing rules', 'Some geospatial data is published, but schema harmonisation, conformance validation, and evidence reports are incomplete', 'Full Art. 7 interoperability with INSPIRE-aligned models, automated conformance validation, documented transformations, and published conformance reports suitable for oversight', 15),

  // GAP-38-M1: law
  q('GOV-PL-12', 'Quality', 'Does the agent implement ISO 25000 SQuaRE §2512 by defining a data and system quality model for petition-to-law datasets (e.g., completeness, accuracy, timeliness, consistency, provenance), computing quality measures, publishing quality dashboards/reports with each release, and retaining audit evidence (measurement definitions, sampling, defect logs, remediation actions)?', 'ISO 25000 SQuaRE §2512', 'No SQuaRE quality measurement: datasets lack defined quality measures, dashboards, or remediation evidence', 'Some quality checks exist, but measures are incomplete, not tied to §2512, or not published with evidence of remediation', 'Full §2512 operationalization with defined quality measures, automated measurement, published quality reports per release, defect/remediation tracking, and audit-ready evidence bundles', 12),

  // GAP-38-M2: law
  q('GOV-PL-13', 'Participation', 'Does the agent implement inclusive public consultation and e-participation in a way that is explicitly mapped to the UN E-Government Survey 2022 e-participation framework (e-information, e-consultation, e-decision-making), including multi-channel participation, accessibility, representativeness monitoring, and published participation metrics suitable for annual benchmarking?', 'UN E-Government Survey 2022 (e-participation)', 'No UN EGov 2022 mapping: participation features are ad hoc and not benchmarkable against 2022 criteria', 'Some participation measures exist, but mapping to UN EGov 2022 components and benchmarking metrics is incomplete', 'Full UN EGov Survey 2022 alignment with mapped participation services, accessibility and inclusion controls, representativeness monitoring, and published benchmark-ready metrics', 10),

  // GAP-38-m1: law
  q('GOV-PL-14', 'Governance', 'Does the program maintain a versioned control-to-citation map for PSI/Open Data and access-to-information obligations (e.g., mapping any legacy 2003/98 references to 2019/1024 where required), with periodic review and automated checks to keep statutory anchors consistent across questions, datasets, and evidence exports?', 'Citation mapping governance', 'No citation governance: references drift and anchors are inconsistent across artifacts', 'Some mapping exists but is manual and inconsistently applied', 'Versioned mapping with periodic review and automated consistency checks ensuring audit-defensible statutory anchors', 6),
];
