// Implementation patch for drug-discovery — all gaps from audit
export const impl13Questions = [
  // GAP-13-C1: ICH Q10 §3.2 (Pharmaceutical Quality System)
  q('HLT-DD-12', 'Governance', 'Does the agent implement a Pharmaceutical Quality System (PQS) aligned to ICH Q10 §3.2, including defined management responsibilities, process performance or product quality monitoring, CAPA, change management, and management review for AI-assisted discovery and AI-influenced CMC or manufacturing activities?', 'ICH Q10 §3.2', 'No PQS; quality governance is ad-hoc, roles are unclear, CAPA or change management are inconsistent or absent', 'Partial PQS with documented roles and some CAPA or change control, but monitoring, management review, and lifecycle governance of AI-driven changes are incomplete', 'Full ICH Q10 §3.2 PQS with governance, KPIs, CAPA effectiveness checks, formal change management (including AI model or process changes), management review cadence, and audit-ready evidence linkage across discovery, development, and manufacturing', 15),
  // GAP-13-C2: ICH Q12 §3.2 (Post-approval change management or lifecycle management)
  q('HLT-DD-13', 'Compliance', 'Does the agent support ICH Q12 §3.2 post-approval change management by defining and controlling Established Conditions (ECs), managing PACMP or predefined change protocols, and maintaining a lifecycle management plan for AI-driven process or model changes that affect CQAs or CPPs?', 'ICH Q12 §3.2', 'No post-approval change governance; ECs or PACMP are not defined and AI-driven changes are uncontrolled', 'Tracks changes and drafts regulatory justifications, but ECs or PACMP scope and reporting categories are inconsistently applied and not audit-ready', 'Full Q12 §3.2 lifecycle management with EC identification, PACMP workflows, change categorization by region, impact assessment tied to QRM, and submission or notification-ready evidence bundles', 15),
  // GAP-13-C3: EU GMP Annex 11 §7.1 (Data integrity)
  q('HLT-DD-14', 'Safety', 'Does the agent implement EU GMP Annex 11 §7.1 data integrity controls for critical data capture (e.g., controlled data entry, verification or second-person review where required, prevention or detection of falsification, and linkage of raw data to reported results) across ELN, LIMS, or instrument integrations?', 'EU GMP Annex 11 §7.1', 'No §7.1 controls; critical data can be entered or edited without effective verification or falsification controls', 'Implements some access controls and audit trails, but critical data verification, raw-data linkage, and falsification detection are inconsistent', 'Comprehensive §7.1 controls with enforced workflows for critical data entry, verification rules, raw-data provenance linkage, anomaly detection, periodic review, and inspection-ready evidence outputs', 12),
  // GAP-13-M1: FDA 21 CFR §211.68 (Automatic, mechanical, electronic equipment)
  q('HLT-DD-15', 'Compliance', 'Does the agent ensure computerized systems used in discovery or CMC labs are validated and controlled per FDA 21 CFR §211.68 (including documented validation, input or output checks, access controls, change control, backup or restore testing, and periodic review) for ELN, LIMS, or instrument integrations?', 'FDA 21 CFR §211.68', 'No CSV or controls; lab computerized systems are unvalidated and rely on informal checks', 'Validates key systems and performs some checks or backups, but validation scope, change control, and periodic review are incomplete or inconsistently evidenced', 'Full §211.68-aligned CSV with risk-based validation, documented checks, controlled configuration, backup or restore verification, and continuous monitoring with audit-ready validation packages', 12),
  // GAP-13-M2: ICH Q8(R2) §2.2 (Design space)
  q('HLT-DD-16', 'Compliance', 'Does the agent define, justify, and govern a design space per ICH Q8(R2) §2.2 (including explicit boundaries, supporting evidence, and change handling within vs outside design space) for AI-assisted development and AI-influenced process optimization?', 'ICH Q8(R2) §2.2', 'No design space; operating ranges and boundaries are informal and not supported by evidence', 'Defines operating ranges and explores multivariate effects, but boundaries, evidence linkage, and within or outside design-space change rules are not consistently enforced', 'Full §2.2 design space governance with evidence-backed boundaries, linkage to CQAs or CPPs, within or outside design-space change workflows, and alignment to Q9 QRM and Q10 control strategy', 10),
];
