// Patch 32 — networked-ecosystems
export const impl32Questions = [
  // GAP-32-C1: OAuth 2.1 §4.1 (PKCE)
  q('TECH-NE-10', 'Security', 'Does the agent implement OAuth 2.1 authorization code flow with PKCE per OAuth 2.1 §4.1 (S256), including strict redirect URI matching, state/nonce anti-CSRF protections, prevention of PKCE downgrade, and auditable evidence (logs/telemetry) that PKCE is enforced for all public clients?', 'OAuth 2.1 §4.1 (PKCE)', 'No PKCE enforcement; authorization code flows can proceed without code_challenge / code_verifier or allow insecure downgrade, and evidence is missing', 'PKCE is implemented for some clients, but enforcement is inconsistent (e.g., legacy exceptions), redirect/state handling is incomplete, or evidence is not audit-ready', 'Full OAuth 2.1 §4.1 PKCE enforcement (S256) for all public clients, strict redirect URI + state/nonce validation, downgrade prevention, continuous conformance testing, and immutable audit logs demonstrating PKCE policy compliance', 15),

  // GAP-32-C2: EU Data Governance Act (Regulation (EU) 2022/868) — Article 12
  q('TECH-NE-11', 'Governance', 'If the agent provides data intermediation services, does it operationalize DGA Art. 12 by enforcing neutrality and separation (no data use for other purposes, ring-fenced operations), implementing appropriate technical and organizational measures for secure intermediation, and maintaining audit-ready evidence (policies, access logs, segregation controls, and periodic compliance attestations)?', 'EU DGA 2022/868 Art. 12', 'No Art. 12 controls; intermediary operations are commingled, data may be reused for other purposes, and evidence is missing', 'Some neutrality/separation controls exist, but segregation, security measures, and audit evidence are incomplete or inconsistently enforced across services/partners', 'Full Art. 12 implementation with enforced non-use constraints, operational separation, technical/organizational controls, continuous monitoring, and audit-ready evidence bundles aligned to competent authority expectations', 15),

  // GAP-32-M1: OWASP API Security Top 10 2023 — API1 (BOLA)
  q('TECH-NE-12', 'Security', 'Does the agent prevent OWASP API1 (Broken Object Level Authorization) by enforcing object ownership/tenant isolation on every object access, using centralized authorization (policy enforcement points), and maintaining automated authorization test coverage (positive/negative cases) with logs suitable for incident reconstruction?', 'OWASP API Top 10 2023 — API1', 'No object-level authorization; endpoints rely on client-provided identifiers without ownership/tenant checks and lack authorization tests', 'Implements some object/tenant checks, but coverage is inconsistent, authorization logic is duplicated, or test evidence is incomplete', 'Full API1 prevention with centralized authorization, consistent ownership/tenant checks, automated authZ test suites per endpoint/resource, and audit-ready access decision logs', 12),

  // GAP-32-m1: EU Data Act 2023/2854 — Article 4
  q('TECH-NE-13', 'Compliance', 'Does the agent implement EU Data Act Art. 4 access obligations in an operationally usable way (secure access interface, timely/continuous access where applicable, SLA evidence for no undue delay, and audit logs proving access was provided to users upon request)?', 'EU Data Act 2023/2854 Art. 4', 'Access is ad hoc/manual; interfaces are insecure or slow, and timeliness/continuity evidence is missing', 'Access interfaces exist, but timeliness/continuity SLAs and evidence are incomplete or inconsistently met', 'Full Art. 4 operationalization with secure interfaces, timeliness/continuity controls, SLA monitoring, and audit-ready access evidence bundles', 8),
];
