// Patch 31 — cognition-to-intelligence
export const impl31Questions = [
  // GAP-31-C1: EU AI Act Art. 50(1) (GPAI transparency)
  q('TECH-CI-10', 'Transparency', 'Does the agent implement EU AI Act Article 50(1) GPAI transparency by (1) clearly disclosing when outputs are AI-generated/AI-assisted, (2) providing provenance (model/system identity, version, and data sources categories), and (3) ensuring disclosures persist across downstream exports/APIs and are auditable (logs/evidence bundles)?', 'EU AI Act Art. 50(1)', 'No GPAI transparency: outputs are presented as human-authored or source-verified with no disclosure or provenance', 'Discloses AI use in some UI surfaces, but provenance and persistence across exports/APIs are inconsistent and not auditable', 'Full Art. 50(1) transparency with consistent disclosure, machine-readable provenance metadata, downstream persistence, and audit-ready disclosure logs for every intelligence artifact', 15),

  // GAP-31-C2: GDPR Art. 22(3)
  q('TECH-CI-11', 'Rights', 'For decisions with legal or similarly significant effects, does the agent implement GDPR Article 22(3) safeguards by enabling (1) human intervention, (2) user ability to express their point of view, and (3) contestation/appeal with documented outcomes, timelines, and audit trails?', 'GDPR Art. 22(3)', 'No safeguard workflow; users cannot request human review or contest outcomes, and decisions are final/opaque', 'Offers a manual escalation path, but viewpoint capture, decision logging, and appeal outcomes are inconsistently recorded', 'End-to-end Art. 22(3) rights workflow with SLA-tracked human review, user submissions, reasoned decisions, outcome notifications, and immutable audit logs linking model outputs to human determinations', 15),

  // GAP-31-C3: ISO/IEC 42001:2023 §6.1
  q('TECH-CI-12', 'Governance', 'Does the agent support ISO/IEC 42001:2023 §6.1 planning by maintaining an AI risk/opportunity register, defining actions with owners and due dates, integrating actions into operational processes (change/release), and tracking effectiveness metrics with evidence suitable for AIMS audit?', 'ISO/IEC 42001:2023 §6.1', 'No planning loop; risks are informal, actions are undocumented, and improvements are ad hoc', 'Maintains a basic risk register and some actions, but integration into ops processes and effectiveness evidence is incomplete', 'Full §6.1 planning with versioned registers, accountable action plans, operational integration, effectiveness measurement, and audit-ready evidence packs', 12),

  // GAP-31-M1: IEEE 7001:2021 §6.3 (Level 3)
  q('TECH-CI-13', 'Transparency', 'Does the agent achieve IEEE 7001:2021 §6.3 Level 3 transparency by producing traceable, reproducible explanations (inputs, transformations, uncertainty), role-appropriate explanation views, and maintained transparency-process artifacts (templates, logs, review records) for each intelligence output?', 'IEEE 7001:2021 §6.3 (Level 3)', 'No IEEE 7001 transparency process; explanations are absent or purely narrative with no traceability', 'Provides explanations and some logs, but lacks Level-3 traceability, reproducibility, and maintained process artifacts', 'Meets Level 3 with traceable explanation records, uncertainty disclosure, role-specific views, and complete transparency-process documentation & review evidence', 10),

  // GAP-31-M2: NIST AI RMF 1.0 GOVERN
  q('TECH-CI-14', 'Governance', 'Does the agent operationalize NIST AI RMF GOVERN by defining accountable roles (RACI), escalation triggers (harm, drift, bias), incident response playbooks, and third-party/model-provider governance (due diligence, monitoring, and termination criteria) for intelligence systems?', 'NIST AI RMF 1.0 GOVERN', 'No operational governance; no defined roles, triggers, or incident playbooks for AI issues', 'Defines some roles and incident handling, but escalation triggers, third-party governance, and evidence are incomplete', 'Full GOVERN implementation with accountable roles, measurable triggers, incident playbooks, third-party governance, and audit-ready governance evidence', 10),
];
