// Implementation patch for future-of-work — all gaps from audit
export const impl16Questions = [
  // GAP-16-C1: NYC Local Law 144
  q('WLT-FW-10', 'Compliance', 'Does the agent support NYC Local Law 144 compliance for Automated Employment Decision Tools (AEDTs), including: (1) annual independent bias audit and publication of a bias audit summary, and (2) required candidate/employee notices about AEDT use, job qualifications assessed, and access to audit information, per NYC Admin Code §20-871 et seq.?', 'NYC Local Law 144 (NYC Admin Code §20-871 et seq.)', 'No NYC LL144 support: no independent bias audit workflow, no audit summary publication, and no candidate/employee notice process for AEDT use', 'Performs some bias testing and can generate an internal report, but independence/audit cadence is unclear and notices/public postings are incomplete or manual', 'Full NYC LL144 readiness: independent bias audit support (metrics, protected classes, selection rates), annual scheduling and evidence retention, public audit-summary generation, and automated compliant notice delivery and tracking for candidates/employees', 15),

  // GAP-16-C2: Illinois AIPA
  q('WLT-FW-11', 'Compliance', 'If the agent is used for AI-assisted video interview analysis, does it comply with Illinois AIPA §15 by providing written notice that AI will be used to analyze the interview, explaining the characteristics evaluated, obtaining candidate consent before analysis, and enforcing a retention/deletion policy for the video and derived data?', 'Illinois AIPA §15', 'No AIPA compliance: no written notice/consent process and no defined retention/deletion controls for interview videos or derived features', 'Provides notice and obtains consent, but explanations are generic and retention/deletion workflows are inconsistent or not auditable', 'End-to-end AIPA compliance with written notice templates, characteristic-explanation generation, explicit consent capture prior to analysis, retention limits, deletion automation on request/policy timelines, and auditable logs of notices/consents/deletions', 12),

  // GAP-16-M1: EEOC AI guidance and ADA
  q('WLT-FW-12', 'Safety', 'Does the agent implement EEOC-aligned safeguards for AI hiring/selection tools by providing (1) accessible assessment workflows and reasonable accommodation pathways (including alternative assessments and assistive-technology compatibility) and (2) documented validation/monitoring of selection procedures to detect disproportionate exclusion of individuals with disabilities?', 'EEOC AI guidance (2023); ADA 42 U.S.C. §12112', 'No accommodation/validation controls: AI screening is used as-is with inaccessible workflows and no accommodation routing or disability-impact monitoring', 'Provides an accommodation request channel and some monitoring, but accommodations are slow/manual and validation/monitoring is incomplete', 'Robust accommodation-by-design with accessible UX, alternative assessment routing, human review SLAs, and ongoing validation/monitoring evidence showing the tool does not disproportionately exclude candidates with disabilities', 12),

  // GAP-16-M2: OECD MNE Guidelines 2023
  q('WLT-FW-13', 'Governance', 'Does the agent support OECD MNE Guidelines 2023 §V by enabling labor-rights due diligence for algorithmic management (impact identification, prevention/mitigation, worker consultation/engagement, grievance intake, and remediation tracking), with evidence outputs suitable for internal/external accountability?', 'OECD MNE Guidelines 2023 §V', 'No OECD due diligence loop: no structured labor-impact assessment, no worker consultation evidence, and grievances/remediation are not tracked', 'Performs periodic assessments and tracks some grievances, but consultation and remediation evidence is incomplete and not connected to algorithmic decisions', 'Full OECD §V operationalization with continuous impact due diligence, documented worker engagement, grievance and remediation case management, and auditable reporting of mitigation effectiveness tied to algorithmic-management changes', 12),

  // GAP-16-m1: Jurisdictional scope gating
  q('WLT-FW-14', 'Governance', 'Does the program maintain a jurisdictional applicability matrix for employment AI features (e.g., AEDT use in NYC; AI video interview analysis in Illinois), and gate feature rollout on completion of location-specific notice/audit/consent requirements with evidence retention?', 'Jurisdictional scope gating for employment AI laws', 'No applicability matrix; feature rollout does not account for jurisdiction-specific compliance triggers', 'Maintains a manual policy memo, but gating and evidence retention are inconsistent across teams and releases', 'Automated scope gating with jurisdiction/role mapping, rollout checks, and evidence bundles demonstrating completion of all location-specific duties prior to deployment', 6),
];
