// Patch 35 — partnerships-prosperity
export const impl35Questions = [
  // GAP-35-C1: law
  q('TECH-PP-10', 'Compliance', 'Does the agent operationalize TRIPS Agreement Article 28 patent rights (rights to prevent third parties from making, using, offering for sale, selling, or importing) for AI-assisted inventions created in partnerships by (1) documenting inventorship/ownership allocation, (2) defining licensing scopes/field-of-use and sublicensing rights, and (3) preparing enforcement-ready evidence (lab notebooks, model training provenance, contribution logs) for disputes and cross-border enforcement?', 'TRIPS Agreement Art. 28', 'No Art. 28 operationalization: AI inventions are shared without clear exclusive-rights scope, licensing authority, or enforcement evidence', 'Defines ownership and basic licenses, but Art. 28 rights scope, field-of-use restrictions, and enforcement evidence bundles are incomplete or inconsistent across partners', 'Full Art. 28-ready patent governance with explicit rights mapping (make/use/sell/import), joint-ownership and licensing playbooks, field-of-use + sublicensing controls, contribution provenance, and enforcement/evidence bundles ready for injunction/invalidity scenarios', 15),

  // GAP-35-C2: law
  q('TECH-PP-11', 'Compliance', 'Does the agent comply with WIPO WPPT Article 7 (performers right of reproduction) by ensuring that partnership projects involving recorded performances (including AI voice/performance capture and synthetic performance generation) have (1) performer consent and scope-limited reproduction licenses, (2) fixation and reproduction tracking, (3) attribution/royalty allocation terms where applicable, and (4) evidence logs linking each use to the relevant authorization?', 'WIPO WPPT Art. 7', 'No WPPT controls: performances are ingested/reproduced/republished via AI tools without performer-authorized reproduction rights or evidence of consent', 'Obtains consent in common cases, but scope limitations (media/territory/term), AI-specific reproduction tracking, and evidence retention are inconsistent', 'Full WPPT Art. 7 compliance with structured performer consent + reproduction licensing, AI capture/synthesis usage logging, scope enforcement (term/territory/media), attribution/royalty metadata, and audit-ready proof of authorization for every reproduction', 12),

  // GAP-35-C3: law
  q('TECH-PP-12', 'Security', 'Does the agent protect trade secrets in partnership data access/sharing under the EU Data Act Article 24 by (1) classifying trade-secret elements in shared datasets, (2) applying technical/organizational safeguards (access controls, secure enclaves/redaction, purpose limitation), (3) enforcing confidentiality + non-disclosure terms downstream, and (4) maintaining evidence to justify withholding/restricting trade-secret data where permitted?', 'EU Data Act 2023/2854 Art. 24', 'No Art. 24 safeguards: partnership data sharing exposes trade secrets without classification, redaction, or enforceable confidentiality controls', 'Implements basic confidentiality and access controls, but trade-secret classification/redaction and downstream enforcement/audit evidence are incomplete', 'Full Data Act Art. 24 trade secret governance with granular classification, redaction/enclave sharing patterns, contract + technical enforcement of confidentiality, and audit-ready evidence supporting any restrictions/withholding decisions', 15),

  // GAP-35-M1: law
  q('TECH-PP-13', 'Governance', 'Where partnership outputs implicate sanitary/phytosanitary (SPS) measures, does the agent apply WTO SPS Agreement Article 5.7 by (1) identifying when scientific evidence is insufficient, (2) implementing provisional measures with documented rationale, (3) actively seeking additional information for a more objective risk assessment, and (4) reviewing/updating measures within a reasonable period with recorded decision trails?', 'WTO SPS Agreement Art. 5.7', 'No SPS 5.7 discipline: measures are recommended/implemented without evidencing insufficiency, provisional status, information-gathering, or review timelines', 'Uses a precautionary approach informally, but does not document provisional status, evidence-gathering plans, and review timelines in a trade-dispute-resilient way', 'Full SPS Art. 5.7 governance with structured triggers for insufficiency, provisional-measure templates, evidence acquisition plans, periodic review SLAs, and audit-ready decision records supporting proportionality and WTO defensibility', 10),

  // GAP-35-m1: law
  q('TECH-PP-14', 'Governance', 'Does the program maintain a WIPO treaty-to-right mapping (WCT vs WPPT) for partnership outputs (authors rights vs performers neighboring rights), ensuring each content workflow (capture, reproduction, distribution, TPM/DRM) is mapped to the correct treaty article(s) and reviewed periodically by legal/compliance?', 'WIPO WCT/WPPT (mapping governance)', 'No mapping governance: WIPO treaty references are generic, WPPT-specific rights are missed, and citations are not reviewed', 'Maintains a mapping in documentation, but it is not kept current with workflow changes or used to gate AI content operations', 'Robust mapping governance with versioning, legal review, and workflow gating so that WCT/WPPT obligations are correctly applied and evidence is produced per right/article', 6),
];
