// Patch 28 — sustainable-real-estate
export const impl28Questions = [
  // GAP-28-C1: EU EPBD 2024 — Art. 9 (zero-emission buildings from 2028 for new buildings)
  q('MOB-RE-10', 'Compliance', 'Does the agent implement EPBD 2024 Article 9 zero-emission building (ZEB) readiness as a time-bound compliance gate, including (1) applicability logic for new buildings from 2028, (2) evidence that the building design and operation meets the ZEB definition, (3) a sequenced upgrade and renovation plan with milestones, and (4) portfolio-level reporting of ZEB readiness and exceptions?', 'EU EPBD 2024 Art. 9 (ZEB from 2028)', 'No ZEB readiness: no applicability logic, no evidence against ZEB definition, and no time-bound upgrade plan', 'Has a roadmap concept and partial evidence, but lacks deadline gating, applicability logic, and auditable ZEB evidence bundles', 'Full Art. 9 ZEB readiness with deadline-based gating, ZEB definition evidence packs, sequenced milestones, exception handling, and portfolio reporting for regulator and investor scrutiny', 15),

  // GAP-28-C2: ISO 50001:2018 — Clause 6.3 (energy review)
  q('MOB-RE-11', 'Governance', 'Does the agent operate an ISO 50001:2018 Clause 6.3 energy review for buildings (and linked EnPIs), including identification of significant energy uses, baseline management, normalization factors (weather and occupancy), action plans, and evidence retention suitable for ISO 50001 certification audits?', 'ISO 50001:2018 Clause 6.3 (Energy review)', 'No energy review: significant energy uses, baselines, normalization are undefined and EnPI governance is absent', 'Performs partial energy review and tracks some EnPIs, but baseline control, normalization, and audit evidence are incomplete', 'Full ISO 50001 Clause 6.3 governance with SEU identification, controlled baselines, normalized EnPIs, action-plan tracking, and auditor-ready evidence packs', 12),

  // GAP-28-M1: GRESB Real Estate Assessment — §3.2 (ESG scoring)
  q('MOB-RE-12', 'Transparency', 'Does the agent manage GRESB Section 3.2 scoring readiness by mapping portfolio data to scoring drivers, enforcing evidence quality requirements (document links, timestamps, ownership), validating completeness before submission, and producing a pre-submission score-delta analysis with remediation tasks?', 'GRESB Real Estate Assessment §3.2', 'No scoring governance: GRESB data is ad hoc, evidence is missing, and submission is not validated', 'Collects most data and some evidence, but scoring-driver coverage and validation are incomplete', 'Full Section 3.2 scoring readiness with scoring-driver mapping, evidence quality enforcement, pre-submission validation, and remediation workflow that maximizes verifiable score outcomes', 10),

  // GAP-28-M2: WELL Building Standard v2 — Air (CO2 and ventilation performance requirements)
  q('MOB-RE-13', 'Wellbeing', 'Does the agent implement WELL v2 Air requirements for CO2 and ventilation performance by enforcing sensor calibration and QA, validating ventilation rates and CO2 thresholds over time, and generating WELL-audit-ready evidence (continuous logs, exceptions, corrective actions, and commissioning records)?', 'WELL v2 — Air (CO2 and ventilation performance)', 'No WELL-grade CO2 control: sensors and calibration are unmanaged and thresholds are not enforced or evidenced', 'Monitors CO2 and flags issues, but calibration, threshold governance, and audit evidence are incomplete', 'Full WELL CO2 and ventilation governance with calibrated sensing, threshold enforcement, corrective action workflows, and auditor-ready evidence packs', 10),

  // GAP-28-M3: EU Taxonomy Regulation 2020/852 — Art. 8 (disclosure KPIs)
  q('MOB-RE-14', 'Transparency', 'Does the agent compute EU Taxonomy Article 8 KPIs for real estate portfolios (taxonomy-eligible vs taxonomy-aligned turnover, CapEx, OpEx) with traceable mappings to underlying assets and activities and reconciliation to financial reporting, including evidence links for eligibility, alignment, DNSH?', 'EU Taxonomy 2020/852 Art. 8', 'No Art. 8 KPI output: taxonomy KPIs are not computed or cannot be reconciled and evidenced', 'Computes some KPIs but mappings, reconciliations, evidence are incomplete', 'Full Art. 8 disclosure readiness with repeatable KPI computation, traceable mappings, reconciliations, and audit-ready evidence bundles', 10),

  // GAP-28-m1: EPBD (SRI governance / delegated acts — citation precision)
  q('MOB-RE-15', 'Governance', 'Does the program maintain an EPBD control-to-article mapping (including SRI) that is reviewed on regulatory updates, so citations and evidence expectations remain audit-defensible over time?', 'EU EPBD 2024 (control mapping governance)', 'No mapping governance: EPBD and SRI references drift and are not reviewed', 'Mapping exists but updates are manual and can lag regulatory changes', 'Versioned EPBD mapping with review workflow and automated checks for citation consistency across the pack', 6),
];
