// Patch 36 — digital-citizens-rights
export const impl36Questions = [
  // GAP-36-C1: eIDAS 2.0 Art. 5a (EUDI Wallet); assurance level high
  q('GOV-DCR-10', 'Compliance', 'Does the agent implement eIDAS 2.0 Article 5a EU Digital Identity Wallet requirements with explicit support for wallet assurance level high, including (1) assurance claim governance, (2) evidence bundles for high assurance (issuance + authentication + attribute attestation), (3) relying-party verification flows, (4) cross-border acceptance checks, and (5) auditable wallet lifecycle controls (issuance, suspension, revocation, recovery)?', 'eIDAS 2.0 Art. 5a (EUDI Wallet); assurance level high', 'No Art. 5a wallet control: wallet assurance level high is not defined, evidenced, or auditably enforced', 'Some wallet features exist (e.g., selective disclosure), but assurance level high governance and evidence are incomplete or non-auditable', 'Full Art. 5a EUDI Wallet implementation with assurance level high governance, relying-party verification, cross-border acceptance, and auditor-ready evidence packs for issuance/authentication/attestation lifecycles', 18),

  // GAP-36-C2: EU AI Act Annex III §8 (high-risk) — lifecycle obligations
  q('GOV-DCR-11', 'Governance', 'For EU AI Act Annex III §8 high-risk use cases in digital identity and citizen-rights systems, does the agent implement the full high-risk lifecycle (risk management system, dataset governance, event logging, technical documentation, post-market monitoring, incident reporting, and a fundamental-rights impact assessment workflow for public-sector deployments), with evidence exports suitable for oversight inquiries?', 'EU AI Act Annex III §8 (high-risk) — lifecycle obligations', 'No Annex III lifecycle: identity AI lacks risk management, data governance, logging, and FRIA evidence', 'Some controls exist (e.g., transparency, incident response), but lifecycle evidence and conformity-assessment readiness are incomplete', 'Full Annex III §8 lifecycle operationalization with conformity-assessment-grade evidence packs, FRIA workflow, and ongoing monitoring/reporting', 18),

  // GAP-36-C3: GDPR Art. 9(2)(a)
  q('GOV-DCR-12', 'Privacy', 'When special-category attributes are stored or shared via the digital identity wallet, does the agent implement GDPR Art. 9(2)(a) explicit consent with (1) purpose-scoped consent prompts, (2) granular attribute-level consent, (3) withdrawal/refresh rules, (4) consent receipt + audit logs, and (5) safeguards against coerced consent in public-service contexts?', 'GDPR Art. 9(2)(a)', 'No explicit-consent controls: special-category attributes are processed/shared without explicit consent evidence or withdrawal handling', 'Consent is captured, but is not granular/purpose-scoped or lacks auditable receipts and withdrawal enforcement', 'Full Art. 9(2)(a) explicit-consent governance with granular consent receipts, withdrawal enforcement, and audit-ready logs tied to attribute disclosure events', 15),

  // GAP-36-M1: ISO/IEC 29115:2013 §7 (AL3)
  q('GOV-DCR-13', 'Security', 'Does the agent implement ISO/IEC 29115:2013 §7 assurance level AL3 for entity authentication (and map wallet flows to AL3), including identity proofing strength, authenticator requirements, binding/recovery, phishing resistance expectations appropriate to AL3, and evidence for auditors that AL3 controls are consistently applied across services?', 'ISO/IEC 29115:2013 §7 (AL3)', 'No AL3 mapping: assurance controls are inconsistent and cannot be evidenced against §7 AL3', 'Some strong auth controls exist, but AL3 mapping and audit evidence are incomplete', 'Full §7 AL3 operationalization with clear control mapping, consistent enforcement, and auditor-ready evidence packs', 12),

  // GAP-36-m1: eIDAS 2.0 (control mapping governance)
  q('GOV-DCR-14', 'Governance', 'Does the program maintain a versioned eIDAS 2.0 control-to-article mapping for the EUDI Wallet (ensuring Art. 5a anchors are used where required), with review on regulatory updates and automated checks for citation consistency across questions and outputs?', 'eIDAS 2.0 (control mapping governance)', 'No mapping governance: citations drift and requested anchors (e.g., Art. 5a) are not consistently used', 'Mapping exists but updates are manual and inconsistently applied', 'Versioned, reviewed control mapping with automated citation-consistency checks and audit-defensible references', 6),
];
