// Patch 30 — privacy-security-mobility
export const impl30Questions = [
  // GAP-30-C1: law
  q('MOB-PS-10', 'Governance', 'Does the agent implement NIST CSF 2.0 GV.OC (Organizational Context) by maintaining (1) mission and business context for mobility privacy and security, (2) stakeholder map (drivers, passengers, pedestrians, regulators, OEMs, suppliers), (3) regulatory obligation register (GDPR, UNECE R155/R156, ETSI EN 303 645, NIS2, etc.), and (4) documented risk appetite and prioritization rules that drive control selection and exception handling?', 'NIST CSF 2.0 GV.OC', 'No governance context: mission, stakeholders, regulatory obligations, and risk appetite are not documented; controls are inconsistent and ad hoc', 'Governance context exists but is incomplete, inconsistently applied, or not linked to control priorities and exception decisions', 'Full GV.OC governance with maintained context and stakeholder mapping, versioned obligation register, risk appetite statements, decision logs for exceptions, and governance outputs that drive privacy and security control prioritization and continuous improvement', 12),

  // GAP-30-C2: law
  q('MOB-PS-11', 'Security', 'Does the agent implement ISO 21434:2021 §9.3 TARA by producing and maintaining item level TARA artifacts (asset identification, threat scenarios, attack path analysis, impact and severity ratings, likelihood and feasibility assessment, risk determination, and risk treatment decisions) with traceability to cybersecurity goals and requirements and evidence of periodic review triggered by changes and incidents?', 'ISO 21434:2021 §9.3 (TARA)', 'No ISO 21434 TARA: threats and attack paths are not systematically analyzed and risk treatment decisions are undocumented', 'Partial TARA exists, but attack path rigor, traceability to requirements, and change triggered review and evidence are incomplete', 'Full §9.3 TARA with structured artifacts, attack path modeling, requirement traceability, change and incident triggered re assessment, and audit ready evidence packs aligned to ISO 21434 expectations', 15),

  // GAP-30-C3: law
  q('MOB-PS-12', 'Compliance', 'Does the agent implement UNECE WP.29 R155 §7.3.3 by operating a CSMS effectiveness and post development monitoring loop, including (1) continuous monitoring for vulnerabilities and cyber events across fleet and backend and supply chain, (2) defined escalation and decision criteria, (3) evidence of corrective actions and verification of effectiveness, and (4) audit ready CSMS records demonstrating ongoing compliance for type approval and surveillance audits?', 'UNECE WP.29 R155 §7.3.3', 'No §7.3.3 loop: monitoring is ad hoc, corrective actions are not evidenced, and CSMS effectiveness cannot be demonstrated for audit and type approval', 'Monitoring and response exist but evidence, effectiveness verification, and audit ready CSMS records are incomplete or inconsistently maintained', 'Full §7.3.3 compliance with continuous monitoring, governed escalation, corrective action and effectiveness verification, and maintained CSMS evidence packs supporting type approval and surveillance audits', 15),

  // GAP-30-M1: law
  q('MOB-PS-13', 'Security', 'Does the agent enforce ETSI EN 303 645 §5.1 by preventing universal default credentials and ensuring unique per device (or unique per user) authentication secrets, including secure onboarding, secure reset behavior, credential rotation and renewal, and evidence that device fleets cannot be accessed via shared defaults?', 'ETSI EN 303 645 §5.1', 'Universal and default credentials exist; onboarding and resets reintroduce shared secrets and the fleet is vulnerable to credential stuffing and mass compromise', 'Unique credentials are used for many devices, but reset and onboarding and rotation controls and evidence are incomplete or inconsistently applied across the fleet', 'Full §5.1 compliance with unique credential governance, secure onboarding and reset flows, rotation support, fleet wide verification tests, and auditable evidence demonstrating absence of universal default passwords and keys', 12),
];
