// Implementation patch for sip-to-sanitation
// All new q() calls extracted from audit gaps
export const impl06Questions = [
  // GAP-06-C1: EU Drinking Water Directive (EU) 2020/2184 Art. 10
  q('ENV-STS-11', 'Governance', 'Does the agent implement the EU Drinking Water Directive 2020/2184 risk-based approach by supporting and evidencing water supply system risk assessment and risk management measures (including documentation, review frequency, and control verification) per Article 10?', 'EU DWD 2020/2184 Art. 10', 'No risk assessment/risk management workflow; compliance relies on periodic testing without a documented risk-based assessment or managed control measures', 'Maintains a documented risk assessment and some risk management actions, but updates are periodic/manual and control verification evidence is incomplete or not audit-ready', 'End-to-end Art. 10 compliance automation: continuous system risk assessment (catchment-to-tap), risk management measure selection/verification, change-triggered review, evidence pack generation for competent authority review, and linkage to monitoring plans and incident response', 15),
  // GAP-06-C2: HELCOM Baltic Sea Action Plan (BSAP)
  q('ENV-STS-12', 'Sustainability', 'Does the agent implement monitoring, decision controls, and reporting aligned to HELCOM Baltic Sea Action Plan (BSAP) commitments relevant to its operations (e.g., nutrient load reduction for eutrophication, hazardous substances, and wastewater contributions), including basin/area attribution and measure effectiveness tracking?', 'HELCOM BSAP', 'No BSAP alignment; discharges and measures are not linked to BSAP objectives/targets and reporting is absent', 'Tracks some nutrient/chemical indicators and reports periodically, but does not attribute loads, manage measures against targets, or demonstrate measure effectiveness over time', 'Full BSAP-aligned governance with load attribution modeling, measure selection and effectiveness tracking, cross-border reporting-ready outputs, and continuous improvement loops tied to BSAP objectives', 12),
  // GAP-06-M1: WHO Guidelines for Drinking-water Quality (4th ed.) §4.1
  q('ENV-STS-13', 'Governance', 'Does the agent ensure Water Safety Plan implementation consistent with WHO GDWQ (4th ed.) §4.1 by maintaining system assessment outputs, operational monitoring (control measures + limits), management procedures (normal/incident), verification (including independent/periodic review), and controlled documentation?', 'WHO GDWQ (4th ed.) §4.1', 'No WSP implementation; elements are missing (system assessment, monitoring, procedures, verification) and documentation is not controlled', 'Implements most WSP components with documented procedures and some verification, but operational monitoring and periodic review are incomplete or not consistently evidenced', 'Comprehensive WSP implementation with continuous operational monitoring, automated verification and review cycles, incident/normal SOP enforcement, controlled documentation, and audit-ready evidence mapped to §4.1 elements', 12),
  // GAP-06-m1: MARPOL Annex IV (incl. Reg. 9/10 equipment approval; Reg. 11 discharge conditions)
  q('ENV-STS-14', 'Compliance', 'Does the agent verify vessel sewage system conformity and operational readiness (approved equipment status, maintenance/inspection records, alarms/bypass detection) alongside MARPOL Annex IV Reg. 11 discharge-condition monitoring?', 'MARPOL Annex IV Reg. 11 (+ equipment approval/operation)', 'No equipment conformity/readiness checks; compliance relies on manual logs and discharge assertions', 'Tracks equipment certificates and maintenance logs, but does not detect bypass/malfunction patterns or reconcile operational readiness with discharge events', 'Integrated compliance with certificate validation, maintenance/condition monitoring, bypass anomaly detection, and evidence linkage to each discharge decision/event', 8),
];
