// Patch 25 — differently-abled
export const impl25Questions = [
  // GAP-25-C1: CRPD Art. 9(2)(b) — accessible information and communications technologies (ICT)
  q('EDU-DA-10', 'Governance', 'Does the agent implement CRPD Article 9(2)(b) accessible-ICT governance by ensuring (1) accessibility-by-design requirements in procurement/third-party integrations (LMS, assessment tools, plugins), (2) accessibility regression testing for releases and AI-generated content, (3) accessible documentation/support channels, and (4) remediation SLAs and accountability for accessibility defects affecting learners with disabilities?', 'CRPD Art. 9(2)(b) (accessible ICT); accessibility-by-design procurement and lifecycle governance', 'No CRPD Art. 9(2)(b) ICT governance; accessibility is treated as ad hoc UI fixes with no procurement controls, regression testing, or remediation accountability', 'Has basic accessibility requirements and some testing, but does not cover third-party procurement controls, AI-generated content checks, or remediation SLAs/accountability end-to-end', 'Full CRPD Art. 9(2)(b) compliance with procurement accessibility clauses, end-to-end accessibility QA (including AI-generated content), third-party conformance evidence, tracked defect remediation SLAs, and governance reporting on accessibility outcomes', 15),

  // GAP-25-M1: WCAG 2.1 §1.4.3 — Contrast (Minimum) 4.5:1
  q('EDU-DA-11', 'Safety', 'Does the agent meet WCAG 2.1 Success Criterion 1.4.3 (Contrast Minimum) by enforcing a 4.5:1 contrast ratio for text (and 3:1 for large text), including for AI-generated content (e.g., overlays, annotations, charts), and by maintaining auditable contrast test results and remediation tracking?', 'WCAG 2.1 SC 1.4.3 (Contrast Minimum) — 4.5:1', 'No contrast controls; text and AI-generated visual elements do not meet 4.5:1 and there is no testing evidence', 'Meets contrast in most templates, but AI-generated content and dynamic states are not systematically checked and evidence is incomplete', 'Full 1.4.3 compliance with automated contrast testing (including dynamic/AI-generated states), design token enforcement, exception handling, and audit-ready evidence + defect remediation tracking', 12),

  // GAP-25-M2: Section 508 — 36 CFR Part 1194.22 (Web-based intranet and internet information and applications)
  q('EDU-DA-12', 'Compliance', 'For U.S. federal/agency procurement contexts, does the agent provide Section 508 §1194.22-mapped evidence for web accessibility (including keyboard access, non-text equivalents, and accessible forms), with conformance documentation that can be packaged for procurement and audit review?', 'Section 508 — 36 CFR Part 1194.22', 'No §1194.22 mapping; cannot produce procurement/audit-ready evidence aligned to legacy Section 508 web criteria', 'Provides partial mapping and some evidence, but coverage and traceability to §1194.22 criteria are incomplete', 'Full §1194.22 mapping with conformance matrix, test evidence attachments, traceability from criteria to implementation, and procurement-ready reporting bundles', 10),

  // GAP-25-m1: UNESCO Salamanca Statement §7
  q('EDU-DA-13', 'Governance', 'Does the agent support Salamanca Statement §7 implementation by enabling ordinary-school inclusion through (1) individualized supports in mainstream settings, (2) educator training/support workflows, (3) resourcing and service coordination (e.g., speech/OT/AT), and (4) monitoring inclusion outcomes (participation, attainment, wellbeing) rather than placement alone?', 'UNESCO Salamanca Statement §7', 'No Salamanca §7 operational support; inclusion is measured only by placement labels, with no supports/resourcing/training workflows', 'Tracks some supports and outcomes, but coordination, training workflows, and inclusion outcome monitoring are incomplete', 'Full Salamanca §7 operationalization with coordinated supports, educator enablement, service delivery tracking, and inclusion outcome dashboards tied to continuous improvement', 8),
];
