// Patch 18 — no-poverty
export const impl18Questions = [
  // GAP-18-C1: ECOA — 15 U.S.C. §1691 (fair lending / nondiscrimination; disparate impact risk management expectations)
  q('WLT-NP-10', 'Fair Lending', 'Does the agent implement fair-lending governance to prevent discriminatory or disparate-impact outcomes in inclusive credit decisions, including (1) protected-class outcome monitoring, (2) explainable drivers and feature review (including proxy detection), (3) periodic independent testing, and (4) documented remediation actions, consistent with ECOA 15 U.S.C. §1691 expectations for nondiscrimination in credit?', 'ECOA 15 U.S.C. §1691; fair lending disparate impact governance', 'No fair-lending governance; no protected-class monitoring or disparate-impact testing is performed for credit approvals, terms, or collections outcomes', 'Performs periodic outcome monitoring and flags potential disparities, but proxy-feature controls, independent testing, and remediation evidence are incomplete', 'Full fair-lending governance with continuous disparity monitoring (approval/price/collections), proxy-feature detection, independent validation/audit trails, remediation workflows, and board-level reporting demonstrating nondiscriminatory inclusion outcomes', 15),

  // GAP-18-C2: U.S. Community Reinvestment Act (CRA) — community reinvestment expectations (assessment area + qualifying lending/service/investment)
  q('WLT-NP-11', 'Governance', 'If the provider is subject to the Community Reinvestment Act (CRA), does the agent support CRA-aligned community reinvestment by (1) mapping products and outreach to assessment areas, (2) measuring lending/service outcomes to low- and moderate-income (LMI) communities, and (3) producing examination-ready evidence of qualifying activities and impact?', 'Community Reinvestment Act (CRA) — community reinvestment and LMI outcomes', 'No CRA support; no assessment area mapping, LMI outcome measurement, or exam-ready evidence of qualifying activities', 'Tracks some LMI outreach and lending metrics, but assessment area alignment and evidence packaging for CRA exams are incomplete', 'Full CRA readiness with assessment-area mapping, LMI outcome dashboards, qualifying activity tagging, exam-ready evidence bundles, and governance reporting aligned to CRA performance context', 12),

  // GAP-18-M1: World Bank / GPFI — 2020 financial inclusion and digital financial services (DFS) guidance
  q('WLT-NP-12', 'Consumer Protection', 'Does the agent implement World Bank / GPFI 2020-aligned responsible DFS controls, including product suitability checks for vulnerable users, transparent total cost disclosures, accessible complaints + dispute resolution SLAs, and fraud/scam resilience (social engineering protections) for low-literacy populations?', 'World Bank GPFI (2020) — responsible DFS / consumer protection', 'No GPFI-aligned DFS controls; suitability, dispute resolution, and scam resilience are not systematically implemented', 'Implements some disclosures and basic complaints intake, but suitability checks, resolution SLAs, and scam/fraud resilience are incomplete', 'Full GPFI-aligned DFS consumer outcomes with suitability gating, total-cost transparency, monitored complaint/dispute SLAs, scam resilience patterns, and auditable reporting of consumer harm reduction', 12),

  // GAP-18-M2: Basel / BCBS — financial inclusion guidance (proportionality, governance, operational risk for inclusive finance)
  q('WLT-NP-13', 'Risk Management', 'Does the agent implement Basel/BCBS-aligned governance for inclusive finance, including proportional risk controls for simplified accounts, agent network operational risk management, fraud/AML control alignment, incident reporting, and board-level oversight of inclusion channel risks?', 'Basel/BCBS — financial inclusion governance and proportionality', 'No prudential inclusion governance; inclusion channels operate without structured operational risk controls or supervisory-ready reporting', 'Some operational risk controls exist, but proportionality rationale, agent network governance, and board-level oversight evidence are incomplete', 'Full BCBS-aligned inclusion governance with proportional controls, agent-channel risk management, incident reporting, supervisory-ready evidence packs, and board-level oversight tied to inclusion outcomes and safety', 10),

  // GAP-18-m1: EU Microfinance Reg §3
  q('WLT-NP-14', 'Compliance', 'For EU microfinance programs, does the agent comply with EU Microfinance Reg §3 requirements (eligibility / conduct obligations as applicable), including customer protections, reporting evidence, and audit-ready documentation for program administrators/supervisors?', 'EU Microfinance Reg §3', 'No EU microfinance compliance support; obligations are not recognized or documented', 'Recognizes EU microfinance obligations at a policy level, but implementation controls and evidence outputs are incomplete', 'Full EU microfinance compliance with obligation mapping, controlled workflows, reporting outputs, and audit-ready evidence for §3 requirements', 6),
];
