// Implementation patch for weave-to-wear
// All new q() calls extracted from audit gaps
export const impl02Questions = [
  // GAP-WW-ILO-C138: ILO Convention C138 (Minimum Age), esp. Arts. 2–3
  q('ENV-WW-10', 'Ethics', 'Does the agent verify minimum-age compliance and hazardous-work protections per ILO Convention C138 (Minimum Age) Articles 2–3 across all textile supply chain tiers, including remediation and monitoring of young-worker conditions?', 'ILO Convention C138 Arts. 2–3', 'No minimum-age controls; audits do not explicitly check C138 thresholds or hazardous-work restrictions; remediation is ad-hoc', 'Agent checks minimum-age records in social audits and flags noncompliance, but coverage is limited to tier-1/2 and remediation tracking is incomplete', 'Continuous minimum-age assurance across tiers with worker-age verification safeguards, hazardous-task controls for young workers, grievance channels, verified remediation closure, and audit-ready evidence trails aligned to C138', 12),
  // GAP-WW-OECD-DDG-GARMENT-III: OECD Due Diligence Guidance for Responsible Supply Chains in the Garment and Footwear Sector, §III
  q('ENV-WW-11', 'Governance', 'Does the agent implement risk-based due diligence for garment & footwear supply chains per OECD Due Diligence Guidance (Garment & Footwear) §III, including supplier mapping, risk identification, mitigation plans, stakeholder engagement, and grievance/complaints mechanisms?', 'OECD DDG Garment & Footwear Sector §III', 'No OECD DDG implementation; supplier risk processes are informal and not aligned to §III expectations', 'Agent performs supplier mapping and basic risk screening, but does not fully operationalize §III (stakeholder engagement, grievance, mitigation effectiveness tracking)', 'Full OECD DDG §III operationalization with end-to-end supplier mapping, structured risk taxonomy, time-bound mitigation and leverage plans, worker/stakeholder engagement loops, grievance intake-to-closure workflow, and effectiveness measurement with auditable evidence', 12),
  // GAP-WW-REACH-ART-57: REACH Regulation (EC) 1907/2006 Art.57 (SVHC criteria)
  q('ENV-WW-12', 'Safety', 'Does the agent operationalize REACH SVHC identification criteria per REACH (EC) 1907/2006 Article 57 (CMR, PBT/vPvB, endocrine disruptors, equivalent concern) and map them to candidate-list screening and substitution decisions for textile chemistries?', 'REACH (EC) 1907/2006 Art.57', 'No SVHC-criteria mapping; only ad-hoc checks against lists without criteria traceability', 'Agent screens against the SVHC candidate list, but cannot explain Art.57 category rationale or prioritize substitution beyond list membership', 'Art.57-aware SVHC governance: criteria-based classification, continuous candidate-list monitoring, substitution planning, concentration/threshold tracking, and auditable rationale for chemical decisions across tiers', 8),
  // GAP-WW-ESPR-2024-1781-ART5-DPP-LINK: EU Ecodesign for Sustainable Products Regulation (EU) 2024/1781 Art.5 (ecodesign requirements) + Art.8 (DPP)
  q('ENV-WW-13', 'Compliance', 'Does the agent ensure Digital Product Passport (DPP) implementation under Regulation (EU) 2024/1781 Article 8 is complete, and that DPP data attributes and lifecycle updates satisfy ecodesign requirements and delegated acts issued under Article 5 for textiles?', 'EU Regulation 2024/1781 Arts. 5 & 8', 'No 2024/1781 alignment; DPP data is incomplete and not mapped to ecodesign delegated-act requirements', 'Agent produces a basic DPP, but does not map required attributes to Art.5 delegated acts or ensure ongoing lifecycle updates', 'Delegated-act-ready DPP: mandatory attributes mapping, interoperable data carrier, signed data integrity, lifecycle updates (repair/reuse/recycling), and compliance evidence generation aligned to Arts.5/8', 8),
];
