"""AMC product feature catalog.

This module records the additional 50 non-security product topics you shared and
maps each to a relevance band for AMC execution planning.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Iterable


class Relevance(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Domain(str, Enum):
    PRODUCTIZATION = "productization"
    DEVX = "developer_experience"
    ORCHESTRATION = "orchestration"
    KNOWLEDGE = "knowledge_data"
    UX = "interaction_ux"
    OBSERVABILITY = "observability"


@dataclass(frozen=True)
class FeatureProposal:
    feature_id: int
    title: str
    lane: Domain
    summary: str
    relevance: Relevance
    amc_fit: bool
    rationale: str
    owner_hint: str
    effort: str
    blockers: tuple[str, ...] = ()


def _features() -> list[FeatureProposal]:
    return [
        # Productization + monetization
        FeatureProposal(
            1,
            "Agent onboarding + connect-accounts wizard",
            Domain.PRODUCTIZATION,
            "Quick set-up flow with OAuth + workflow selection + first-run success path.",
            Relevance.HIGH,
            True,
            "Directly enables first-time user activation and paid onboarding flow.",
            "PM + Fullstack",
            "2–4 weeks",
            ("OAuth providers and credentials vault still evolving",),
        ),
        FeatureProposal(
            2,
            "Usage metering + billing for agent runs",
            Domain.PRODUCTIZATION,
            "Meter model/tool/browser minutes per tenant and bill by value-based unit.",
            Relevance.HIGH,
            True,
            "Core recurring revenue foundation for self-serve and enterprise billing.",
            "Platform + Analytics",
            "4–6 weeks",
            ("Billing provider integration", "fraud/chargeback guardrails"),
        ),
        FeatureProposal(
            3,
            "White-label agency agent launcher",
            Domain.PRODUCTIZATION,
            "Client-spawned branded environments with isolated data and templates.",
            Relevance.HIGH,
            True,
            "High ARR potential by letting agencies resell AMC-enabled workflows.",
            "Fullstack + DevEx",
            "4–5 weeks",
            ("Tenant branding pipeline", "template governance"),
        ),
        FeatureProposal(
            4,
            "Outcome-based pricing wrapper",
            Domain.PRODUCTIZATION,
            "Outcome tracking + take-rate and incentive models.",
            Relevance.MEDIUM,
            True,
            "Monetization lever, but needs stronger telemetry before launch.",
            "Revenue + Analytics",
            "6+ weeks",
            ("Reliable outcome attribution", "legal/tax treatment"),
        ),
        FeatureProposal(
            5,
            "Subscription retention autopilot",
            Domain.OBSERVABILITY,
            "Monitor health signals and trigger retention flows before churn.",
            Relevance.HIGH,
            True,
            "Directly improves MRR stability for AMC deployments.",
            "Growth",
            "3–5 weeks",
            ("Retention datasets", "notification policy"),
        ),
        # Developer experience
        FeatureProposal(
            6,
            "Agent scaffolding CLI",
            Domain.DEVX,
            "Generate project skeleton, tool wrappers, logging, tests, and deploy scripts.",
            Relevance.HIGH,
            True,
            "Strong fit: lowers friction for builders in AMC ecosystem.",
            "Platform",
            "3–4 weeks",
            ("Scaffold standard for policy manifest compatibility",),
        ),
        FeatureProposal(
            7,
            "SOP -> workflow compiler",
            Domain.DEVX,
            "Convert SOP docs into runnable workflow definitions with validation.",
            Relevance.HIGH,
            True,
            "Bridges process design teams to deployable automation using AMC.",
            "Docs + Engineering",
            "4–6 weeks",
            ("Workflow DSL maturity", "human approval steps"),
        ),
        FeatureProposal(
            8,
            "UI recorder -> browser automation generator",
            Domain.DEVX,
            "Record human actions in browser and convert to robust selectors/chkpoints.",
            Relevance.MEDIUM,
            True,
            "Useful, but high maintenance with browser drift across sites.",
            "Automation",
            "5–7 weeks",
            ("Selector self-healing", "site drift strategy"),
        ),
        FeatureProposal(
            9,
            "Tool wrapper generator from OpenAPI/Postman",
            Domain.DEVX,
            "Generate typed connectors from API specs with retry + validation.",
            Relevance.HIGH,
            True,
            "Immediate quality uplift for onboarding external tools into AMC.",
            "Platform",
            "3–4 weeks",
            ("Spec compatibility coverage",),
        ),
        FeatureProposal(
            10,
            "Prompt+workflow version control",
            Domain.DEVX,
            "Git-like prompt/workflow diff, rollback, and release tagging.",
            Relevance.HIGH,
            True,
            "Critical for reliability and post-incident traceability.",
            "Core Platform",
            "2–3 weeks",
            ("History storage", "large artifact compression"),
        ),
        FeatureProposal(
            11,
            "Deterministic replay debugger",
            Domain.DEVX,
            "Replay inputs/actions/state transitions for each run.",
            Relevance.HIGH,
            True,
            "Strong for debugging failures and proving behavior to enterprises.",
            "Watch + Score",
            "4–6 weeks",
            ("Storage footprint", "PII redaction in traces"),
        ),
        FeatureProposal(
            12,
            "Local dev environment with mocked tools",
            Domain.DEVX,
            "Safe local execution with deterministic stubs and contract tests.",
            Relevance.HIGH,
            True,
            "Critical for secure dev velocity and regression checks.",
            "DevEx",
            "3–5 weeks",
            ("Comprehensive connector mocks",),
        ),
        FeatureProposal(
            13,
            "Workflow template marketplace",
            Domain.DEVX,
            "Packaged workflows with versioned revenue-sharing model.",
            Relevance.MEDIUM,
            True,
            "Growth asset but secondary to core trust stack.",
            "Growth + Product",
            "6–8 weeks",
            ("Marketplace moderation", "licensing model"),
        ),
        FeatureProposal(
            14,
            "Auto documentation generator",
            Domain.DEVX,
            "Generate docs from workflows/tests, incl limitations and assumptions.",
            Relevance.MEDIUM,
            True,
            "Supports onboarding and compliance documentation quality.",
            "Docs + Platform",
            "2–3 weeks",
            ("Documentation style and ownership",),
        ),
        FeatureProposal(
            15,
            "Tool contract validator",
            Domain.DEVX,
            "Schema conformance + auto-repair suggestions for tool calls.",
            Relevance.HIGH,
            True,
            "Directly prevents unsafe/broken integrations before execution.",
            "Core Platform",
            "3–4 weeks",
            ("Backwards compatibility with existing tool specs",),
        ),
        # orchestration + reliability
        FeatureProposal(
            16,
            "Durable workflow engine with checkpoints",
            Domain.ORCHESTRATION,
            "Checkpoint/resume support for multi-hour tasks.",
            Relevance.HIGH,
            True,
            "Major upgrade for long-running use cases and trust continuity.",
            "Enforce + Watch",
            "6–8 weeks",
            ("Idempotency model", "state snapshot format"),
        ),
        FeatureProposal(
            17,
            "Event router for triggers",
            Domain.ORCHESTRATION,
            "Webhook/email/db-change ingress with routing and context enrichment.",
            Relevance.HIGH,
            True,
            "Important for production integrations and automation reliability.",
            "Core Platform",
            "3–5 weeks",
            ("Replay idempotency", "signature verification"),
        ),
        FeatureProposal(
            18,
            "Job queue with priorities + SLA",
            Domain.ORCHESTRATION,
            "Per-tenant/task queue priorities and hard completion policies.",
            Relevance.HIGH,
            True,
            "Needed for predictable operational behavior under load.",
            "Core Platform",
            "4–6 weeks",
            ("Queue persistence", "dead-letter handling"),
        ),
        FeatureProposal(
            19,
            "Resumable browser sessions service",
            Domain.ORCHESTRATION,
            "Persist cookies/page state across agent sessions.",
            Relevance.MEDIUM,
            True,
            "Useful but scoped for portal-heavy workflows rather than initial core.",
            "Automation",
            "5–7 weeks",
            ("Browser state security and isolation", "storage size"),
        ),
        FeatureProposal(
            20,
            "Retry/backoff and smart rerun engine",
            Domain.ORCHESTRATION,
            "Retry only failed segment with preserved context.",
            Relevance.HIGH,
            True,
            "Highly reliable execution and lower operator burden.",
            "Enforce",
            "2–3 weeks",
            ("Failure taxonomy quality",),
        ),
        FeatureProposal(
            21,
            "Compensation/rollback workflows",
            Domain.ORCHESTRATION,
            "Auto-rollback patterns for partial failures.",
            Relevance.HIGH,
            True,
            "Risk-limiting capability for transactional automation.",
            "Enforce",
            "4–6 weeks",
            ("Compensation catalog", "business-specific semantics"),
        ),
        FeatureProposal(
            22,
            "Multi-tenant isolation and client sandboxes",
            Domain.ORCHESTRATION,
            "Strict tenant split for workflows/logs/billing.",
            Relevance.HIGH,
            True,
            "Non-negotiable for AMC as a hosted product.",
            "Watch + Vault",
            "3–4 weeks",
            ("Cross-tenant auditability", "shared infra boundaries"),
        ),
        FeatureProposal(
            23,
            "Rate-limit manager across APIs",
            Domain.ORCHESTRATION,
            "Central throttling + scheduling for external integrations.",
            Relevance.HIGH,
            True,
            "Prevents cascading failures from dependency limits.",
            "Enforce",
            "2–3 weeks",
            ("Connector-specific policies",),
        ),
        FeatureProposal(
            24,
            "Human escalation queue",
            Domain.ORCHESTRATION,
            "Ambiguous cases routed to humans with continuation support.",
            Relevance.MEDIUM,
            True,
            "Great quality safety net but not trust-exclusive.",
            "Watch + UX",
            "2–4 weeks",
            ("Assignment UX", "state handoff contract"),
        ),
        FeatureProposal(
            25,
            "Workflow rollout manager",
            Domain.ORCHESTRATION,
            "Gradual staged rollout (10% canary → expand).",
            Relevance.HIGH,
            True,
            "Protects trust and avoids production regressions at change time.",
            "Operations",
            "3–4 weeks",
            ("Metric-driven promotion thresholds",),
        ),
        # knowledge/data plumbing
        FeatureProposal(
            26,
            "Continuous docs ingestion + change summaries",
            Domain.KNOWLEDGE,
            "Weekly summaries and action extraction from doc updates.",
            Relevance.MEDIUM,
            True,
            "Useful for evidence quality but not critical in first week.",
            "Docs + AI Ops",
            "3–5 weeks",
            ("Source connector coverage",),
        ),
        FeatureProposal(
            27,
            "Preference and persona manager",
            Domain.KNOWLEDGE,
            "Persistent style and behavioral preferences for outputs.",
            Relevance.HIGH,
            True,
            "Improves consistency across branded deployments.",
            "Core/UX",
            "2–3 weeks",
            ("Conflict policy with security controls",),
        ),
        FeatureProposal(
            28,
            "Ticket/email to searchable KB",
            Domain.KNOWLEDGE,
            "Mine support history into structured Q&A and snippets.",
            Relevance.MEDIUM,
            True,
            "Value-add for support teams and quality perception.",
            "Knowledge",
            "4–6 weeks",
            ("PII handling", "quality ranking"),
        ),
        FeatureProposal(
            29,
            "Domain glossary + terminology enforcement",
            Domain.KNOWLEDGE,
            "Controlled terminology/branding in all outputs.",
            Relevance.MEDIUM,
            True,
            "Quality + brand compliance layer with moderate scope.",
            "Watch + Core",
            "1–2 weeks",
            ("Terminology governance across connectors",),
        ),
        FeatureProposal(
            30,
            "Unstructured-to-structured extractor",
            Domain.KNOWLEDGE,
            "Convert docs/emails/notes to normalized tables/entities.",
            Relevance.HIGH,
            True,
            "Foundation for reliable downstream workflows and scoring.",
            "Data",
            "4–6 weeks",
            ("OCR accuracy", "entity schemas"),
        ),
        FeatureProposal(
            31,
            "Context pack generator",
            Domain.KNOWLEDGE,
            "Build minimal, task-specific context for each action.",
            Relevance.HIGH,
            True,
            "Reduces context waste and improves response quality/cost.",
            "Score + UX",
            "2–4 weeks",
            ("Context retrieval quality metrics",),
        ),
        FeatureProposal(
            32,
            "Incremental sync connectors",
            Domain.KNOWLEDGE,
            "Delta sync across internal systems to reduce refresh cost.",
            Relevance.HIGH,
            True,
            "Operationally efficient and important for accurate state.",
            "Data",
            "3–5 weeks",
            ("Connector change webhook coverage",),
        ),
        FeatureProposal(
            33,
            "Knowledge graph builder for ops",
            Domain.KNOWLEDGE,
            "Entity relationship graph for customers/contracts/invoices/tickets.",
            Relevance.MEDIUM,
            True,
            "High value for mature deployments, deferred for phase 2.",
            "Data",
            "8+ weeks",
            ("Graph engine complexity", "PII boundaries"),
        ),
        FeatureProposal(
            34,
            "Translation memory + localization store",
            Domain.KNOWLEDGE,
            "Keep wording consistency across languages.",
            Relevance.LOW,
            False,
            "Strong quality feature, but not in first AMC trust MVP wave.",
            "Global product team",
            "5+ weeks",
            ("Localization workflows", "legal language review"),
        ),
        FeatureProposal(
            35,
            "Data quality monitor for inputs",
            Domain.KNOWLEDGE,
            "Detect missing/stale/duplicate fields and auto-route fixes.",
            Relevance.HIGH,
            True,
            "Directly improves reliability of scoring and automation decisions.",
            "Watch",
            "3–4 weeks",
            ("Quality thresholds by tenant",),
        ),
        # interaction and channels
        FeatureProposal(
            36,
            "Omnichannel inbox unifier",
            Domain.UX,
            "Single thread model across WhatsApp/email/web with history coherence.",
            Relevance.MEDIUM,
            True,
            "Expands operational channels; good strategic extension.",
            "UX + Integrations",
            "6–8 weeks",
            ("Channel-specific privacy controls",),
        ),
        FeatureProposal(
            37,
            "Voice-call intake agent",
            Domain.UX,
            "Inbound phone-style capture to structured intents/tickets.",
            Relevance.MEDIUM,
            True,
            "Nice growth play, requires voice infra and compliance work.",
            "Telephony",
            "6+ weeks",
            ("Telephony stack", "recording consents"),
        ),
        FeatureProposal(
            38,
            "Multimodal intake",
            Domain.UX,
            "Accept screenshots/audio/files and auto-extract structured inputs.",
            Relevance.MEDIUM,
            True,
            "Useful for non-text workflows, with stronger parsing complexity.",
            "Knowledge",
            "5+ weeks",
            ("Media parser quality", "security scanning"),
        ),
        FeatureProposal(
            39,
            "Self-serve portal for agent tasks",
            Domain.UX,
            "Customer UI to submit jobs, track progress, download outputs.",
            Relevance.HIGH,
            True,
            "Good product completeness for SMB clients and support reduction.",
            "Product",
            "4–6 weeks",
            ("Auth + tenancy", "job-state UX design"),
        ),
        FeatureProposal(
            40,
            "Draft -> approve -> send UI",
            Domain.UX,
            "Human review/approval UI for outbound outputs.",
            Relevance.HIGH,
            True,
            "Very relevant for trustworthy adoption in communication workflows.",
            "Product",
            "3–5 weeks",
            ("Integration with channel-level controls",),
        ),
        FeatureProposal(
            41,
            "Personalized output styles by recipient",
            Domain.UX,
            "Role-aware tone/structure mapping for output routing.",
            Relevance.MEDIUM,
            True,
            "Improves conversion quality and internal adoption.",
            "Knowledge",
            "2–3 weeks",
            ("Audience model quality",),
        ),
        FeatureProposal(
            42,
            "Proactive reminders + follow-ups",
            Domain.UX,
            "Opt-in reminder flows for missing info and renewals.",
            Relevance.MEDIUM,
            True,
            "Good retention lever but must avoid spam and privacy misfires.",
            "Growth",
            "2–4 weeks",
            ("Opt-in rules", "timezone scheduling"),
        ),
        FeatureProposal(
            43,
            "Team collaboration mode",
            Domain.UX,
            "Task handoff between agents and humans with ownership and state.",
            Relevance.HIGH,
            True,
            "Critical for real operations beyond solo operators.",
            "Product",
            "4–6 weeks",
            ("Notification and audit model",),
        ),
        FeatureProposal(
            44,
            "Multilingual flow designer",
            Domain.UX,
            "Language-aware flow authoring and branching.",
            Relevance.LOW,
            False,
            "Important for global expansion, can wait until English-native product is stable.",
            "Product",
            "6+ weeks",
            ("Localization quality", "translation maintenance"),
        ),
        FeatureProposal(
            45,
            "Accessibility-first agent UX",
            Domain.UX,
            "Keyboard/screen reader/voice support in operator surfaces.",
            Relevance.LOW,
            False,
            "Great enterprise quality bar, but lower priority for AMC launch phase.",
            "UX",
            "5–7 weeks",
            ("Design and testing discipline",),
        ),
        # observability and improvement
        FeatureProposal(
            46,
            "Agent run analytics dashboard",
            Domain.OBSERVABILITY,
            "Success rate, time saved, ROI, and SLA view by workflow.",
            Relevance.HIGH,
            True,
            "Core visibility needed for pricing, trust, and operations.",
            "Analytics",
            "3–5 weeks",
            ("Metric definitions", "report governance"),
        ),
        FeatureProposal(
            47,
            "Cost + latency optimization router",
            Domain.OBSERVABILITY,
            "Per-task model/tool routing for quality + cost trade-offs.",
            Relevance.HIGH,
            True,
            "Directly tied to operating cost and AMC competitiveness.",
            "Ops + Platform",
            "4–6 weeks",
            ("Quality score model", "model compatibility matrix"),
        ),
        FeatureProposal(
            48,
            "A/B testing platform for agents",
            Domain.OBSERVABILITY,
            "Run parallel prompt/workflow/model experiments with auto winner.",
            Relevance.HIGH,
            True,
            "Essential for continuous improvement without blind guesswork.",
            "Analytics",
            "3–6 weeks",
            ("Experiment attribution", "guardrails for harmful prompts"),
        ),
        FeatureProposal(
            49,
            "Failure clustering + root cause summaries",
            Domain.OBSERVABILITY,
            "Group failures by pattern and suggest fixes.",
            Relevance.HIGH,
            True,
            "Excellent for reliability engineering and on-call burden reduction.",
            "Watch",
            "4–6 weeks",
            ("Clustering accuracy", "fix suggestion quality"),
        ),
        FeatureProposal(
            50,
            "Feedback-to-improvement loop",
            Domain.OBSERVABILITY,
            "Capture corrections and drive template/memory refinement over time.",
            Relevance.HIGH,
            True,
            "Direct path to measurable quality gains and customer trust.",
            "Score + Learning",
            "3–5 weeks",
            ("Feedback trust, abuse resistance",),
        ),
    ]


def get_features(relevance: Relevance | None = None, amc_fit_only: bool = False) -> list[FeatureProposal]:
    feats = _features()
    if amc_fit_only:
        feats = [f for f in feats if f.amc_fit]
    if relevance is not None:
        feats = [f for f in feats if f.relevance == relevance]
    return feats


def count_features() -> int:
    return len(_features())


def select_high_impact(limit: int = 12) -> list[FeatureProposal]:
    """Return top high-fit, high relevance items for fast execution."""
    ordered = [f for f in _features() if f.amc_fit and f.relevance == Relevance.HIGH]
    return ordered[:max(0, limit)]


def as_dicts(features: Iterable[FeatureProposal]) -> list[dict[str, object]]:
    return [
        {
            "feature_id": f.feature_id,
            "title": f.title,
            "lane": f.lane.value,
            "summary": f.summary,
            "relevance": f.relevance.value,
            "amc_fit": f.amc_fit,
            "rationale": f.rationale,
            "owner_hint": f.owner_hint,
            "effort": f.effort,
            "blockers": list(f.blockers),
        }
        for f in features
    ]
