"""AMC Product — Agent Scaffolding CLI (Feature 6).

Generates project skeletons for AMC-compatible agents, including:
- Directory structure with amc/ package
- Policy manifest (amc_policy.json)
- Tool wrapper stubs
- Logging setup
- Test scaffolding
- Deploy script skeleton

The generator returns file paths and content as strings so it can be used
headlessly (programmatically or via CLI) without touching the filesystem
unless explicitly requested.

Revenue path: reduces builder friction → faster ecosystem growth → more
deployments on AMC platform (Lever C → A pipeline).
"""
from __future__ import annotations

import json
import textwrap
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

import structlog

log = structlog.get_logger(__name__)


class AgentTemplate(str, Enum):
    BASIC = "basic"                # Simple single-tool agent
    MULTI_TOOL = "multi_tool"     # Multiple tool connectors
    BROWSER_AUTOMATION = "browser_automation"  # Browser-based workflow
    DATA_PIPELINE = "data_pipeline"  # Data extract-transform-load
    APPROVAL_FLOW = "approval_flow"  # Human-in-the-loop workflow


@dataclass
class ScaffoldFile:
    """A single file to be generated."""
    path: str          # relative path within project
    content: str       # file content
    is_binary: bool = False

    def write_to(self, base: Path) -> Path:
        target = base / self.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(self.content, encoding="utf-8")
        return target


@dataclass
class ScaffoldProject:
    """Collection of generated files forming a complete agent project."""
    agent_name: str
    template: AgentTemplate
    files: list[ScaffoldFile] = field(default_factory=list)
    description: str = ""

    @property
    def file_count(self) -> int:
        return len(self.files)

    @property
    def file_paths(self) -> list[str]:
        return [f.path for f in self.files]

    def write_to_disk(self, output_dir: str | Path) -> Path:
        """Write all scaffold files to disk. Returns project root."""
        base = Path(output_dir) / self.agent_name.replace(" ", "_").lower()
        for f in self.files:
            f.write_to(base)
        log.info("scaffolding.written", agent=self.agent_name, path=str(base), files=len(self.files))
        return base


# ---------------------------------------------------------------------------
# Content generators
# ---------------------------------------------------------------------------


def _policy_manifest(agent_name: str, tools: list[str]) -> str:
    """Generate amc_policy.json compatible with the AMC enforce layer."""
    manifest = {
        "manifest_version": "1.0",
        "agent_name": agent_name,
        "description": f"AMC policy manifest for {agent_name}",
        "allow_list": [
            {
                "tool": t,
                "categories": ["read_only"],
                "require_trust": "trusted",
            }
            for t in tools
        ],
        "deny_list": ["exec", "eval", "subprocess"],
        "session_trust_default": "untrusted",
        "rate_limits": {
            "max_tool_calls_per_minute": 60,
            "max_model_calls_per_minute": 20,
        },
        "audit": {
            "receipt_level": "full",
            "pii_redact": True,
        },
    }
    return json.dumps(manifest, indent=2)


def _main_py(agent_name: str, tools: list[str], template: AgentTemplate) -> str:
    tool_imports = "\n".join(f"from .tools.{t} import {t}_tool" for t in tools)
    tool_registry = ", ".join(f'"{t}": {t}_tool' for t in tools)
    return textwrap.dedent(f"""\
        \"\"\"
        {agent_name} — AMC-compatible agent entry point.
        Generated by AMC scaffolding CLI (feature-6).
        \"\"\"
        from __future__ import annotations

        import asyncio
        import structlog

        from amc.watch.w1_receipts import get_ledger
        from amc.core.models import SessionTrust, ToolCategory
        from .config import AgentConfig

        {tool_imports}

        log = structlog.get_logger(__name__)

        TOOL_REGISTRY = {{
            {tool_registry}
        }}


        async def run(task: dict, config: AgentConfig | None = None) -> dict:
            \"\"\"Execute a task using this agent.\"\"\"
            cfg = config or AgentConfig()
            log.info("{agent_name}.run", task_keys=list(task.keys()))

            tool_name = task.get("tool")
            if tool_name not in TOOL_REGISTRY:
                return {{"error": f"Unknown tool: {{tool_name}}"}}

            tool_fn = TOOL_REGISTRY[tool_name]
            result = await tool_fn(task.get("params", {{}}), cfg)

            # Record receipt for auditability
            await get_ledger().record(
                session_id=task.get("session_id", "local"),
                sender_id=task.get("actor", "agent"),
                trust_level=SessionTrust.TRUSTED,
                tool_name=tool_name,
                tool_category=ToolCategory.READ_ONLY,
                parameters_redacted=task.get("params", {{}}),
                outcome_summary=str(result)[:200],
            )

            return result


        if __name__ == "__main__":
            asyncio.run(run({{"tool": "{tools[0] if tools else 'example'}", "params": {{}}}}))
    """)


def _config_py(agent_name: str) -> str:
    return textwrap.dedent(f"""\
        \"\"\"Configuration for {agent_name}.\"\"\"
        from __future__ import annotations
        from dataclasses import dataclass, field
        from typing import Any


        @dataclass
        class AgentConfig:
            \"\"\"Configurable agent settings (injected at runtime).\"\"\"
            max_retries: int = 3
            timeout_seconds: int = 30
            dry_run: bool = False
            metadata: dict[str, Any] = field(default_factory=dict)
    """)


def _tool_stub(tool_name: str) -> str:
    return textwrap.dedent(f"""\
        \"\"\"Tool stub: {tool_name}.

        Replace this stub with a real implementation.
        Keep the async signature and return a serializable dict.
        \"\"\"
        from __future__ import annotations
        from typing import Any
        import structlog

        log = structlog.get_logger(__name__)


        async def {tool_name}_tool(params: dict[str, Any], config: Any) -> dict[str, Any]:
            \"\"\"Execute the {tool_name} tool with the given params.\"\"\"
            log.info("{tool_name}.called", params_keys=list(params.keys()))

            if config.dry_run:
                return {{"dry_run": True, "tool": "{tool_name}", "params": params}}

            # TODO: implement real {tool_name} logic here
            raise NotImplementedError("{tool_name} tool not yet implemented")
    """)


def _test_file(agent_name: str, tools: list[str]) -> str:
    imports = "\n".join(f"from {agent_name.lower()}.tools.{t} import {t}_tool" for t in tools)
    test_cases = "\n\n".join(
        textwrap.dedent(f"""\
            @pytest.mark.asyncio
            async def test_{t}_tool_dry_run() -> None:
                config = AgentConfig(dry_run=True)
                result = await {t}_tool({{}}, config)
                assert result.get("dry_run") is True
        """)
        for t in tools
    )
    return textwrap.dedent(f"""\
        \"\"\"Tests for {agent_name} agent tools.\"\"\"
        import pytest
        {imports}
        from {agent_name.lower()}.config import AgentConfig


        {test_cases}
    """)


def _requirements_txt(template: AgentTemplate) -> str:
    base = ["fastapi>=0.115.0", "pydantic>=2.0.0", "structlog>=24.0.0", "httpx>=0.27.0"]
    if template == AgentTemplate.BROWSER_AUTOMATION:
        base.append("playwright>=1.44.0")
    if template == AgentTemplate.DATA_PIPELINE:
        base.extend(["pandas>=2.0.0", "sqlalchemy>=2.0.0"])
    return "\n".join(base) + "\n"


def _init_py(module_name: str) -> str:
    return f'"""AMC agent module: {module_name}."""\n'


def _readme(agent_name: str, template: AgentTemplate, tools: list[str]) -> str:
    return textwrap.dedent(f"""\
        # {agent_name}

        > Generated by AMC Agent Scaffolding CLI — template: `{template.value}`

        ## Overview

        This agent implements the **{template.value}** workflow pattern.
        It is compatible with the AMC enforce/watch/receipt stack out of the box.

        ## Tools

        {chr(10).join(f'- `{t}`' for t in tools)}

        ## Quick Start

        ```bash
        python -m pip install -r requirements.txt
        python -m {agent_name.lower()}.main
        ```

        ## Policy

        Edit `amc_policy.json` to configure trust levels, rate limits,
        and tool allow/deny lists before deploying to a production AMC runtime.

        ## Testing

        ```bash
        pytest tests/ -v
        ```

        ## AMC Fit

        This project was scaffolded to run inside the AMC runtime.
        Ensure `AMC_POLICY_FILE` points to `amc_policy.json` and
        `AMC_ENV` is set to `production` before deployment.
    """)


def _deploy_sh(agent_name: str) -> str:
    slug = agent_name.lower().replace(" ", "_")
    return textwrap.dedent(f"""\
        #!/usr/bin/env bash
        # Deploy script for {agent_name}
        set -euo pipefail

        AGENT_NAME="{slug}"
        AMC_ENV="${{AMC_ENV:-staging}}"
        AMC_TENANT_ID="${{AMC_TENANT_ID:-local}}"

        echo "[deploy] Deploying $AGENT_NAME to $AMC_ENV (tenant=$AMC_TENANT_ID)"

        # Validate policy manifest
        python -c "import json; json.load(open('amc_policy.json'))" && echo "[deploy] Policy manifest OK"

        # Run tests
        python -m pytest tests/ -q && echo "[deploy] Tests passed"

        # Package
        python -m build --wheel --outdir dist/

        echo "[deploy] Done. Upload dist/ to AMC deployment endpoint."
    """)


# ---------------------------------------------------------------------------
# AgentScaffolder
# ---------------------------------------------------------------------------


class AgentScaffolder:
    """Generates AMC-compatible agent project files."""

    # Default tools per template
    _DEFAULT_TOOLS: dict[AgentTemplate, list[str]] = {
        AgentTemplate.BASIC: ["search", "summarize"],
        AgentTemplate.MULTI_TOOL: ["search", "summarize", "email", "calendar"],
        AgentTemplate.BROWSER_AUTOMATION: ["navigate", "extract", "click"],
        AgentTemplate.DATA_PIPELINE: ["fetch_data", "transform", "load"],
        AgentTemplate.APPROVAL_FLOW: ["draft", "approve", "send"],
    }

    def generate(
        self,
        agent_name: str,
        template: AgentTemplate = AgentTemplate.BASIC,
        tools: list[str] | None = None,
        description: str = "",
    ) -> ScaffoldProject:
        """Generate a complete scaffold project and return it."""
        slug = agent_name.lower().replace(" ", "_")
        selected_tools = tools or self._DEFAULT_TOOLS.get(template, ["example"])

        project = ScaffoldProject(
            agent_name=slug,
            template=template,
            description=description or f"AMC agent: {agent_name} ({template.value} template)",
        )

        # Root files
        project.files.extend([
            ScaffoldFile("README.md", _readme(agent_name, template, selected_tools)),
            ScaffoldFile("requirements.txt", _requirements_txt(template)),
            ScaffoldFile("amc_policy.json", _policy_manifest(agent_name, selected_tools)),
            ScaffoldFile("deploy.sh", _deploy_sh(agent_name)),
            ScaffoldFile("pyproject.toml", self._pyproject_toml(slug)),
        ])

        # Agent package
        project.files.extend([
            ScaffoldFile(f"{slug}/__init__.py", _init_py(slug)),
            ScaffoldFile(f"{slug}/main.py", _main_py(agent_name, selected_tools, template)),
            ScaffoldFile(f"{slug}/config.py", _config_py(agent_name)),
            ScaffoldFile(f"{slug}/tools/__init__.py", _init_py("tools")),
        ])

        # Tool stubs
        for tool in selected_tools:
            project.files.append(
                ScaffoldFile(f"{slug}/tools/{tool}.py", _tool_stub(tool))
            )

        # Tests
        project.files.extend([
            ScaffoldFile("tests/__init__.py", ""),
            ScaffoldFile("tests/test_tools.py", _test_file(agent_name, selected_tools)),
        ])

        log.info(
            "scaffolding.generated",
            agent=agent_name,
            template=template.value,
            tools=selected_tools,
            file_count=len(project.files),
        )
        return project

    @staticmethod
    def _pyproject_toml(slug: str) -> str:
        return textwrap.dedent(f"""\
            [build-system]
            requires = ["setuptools>=68"]
            build-backend = "setuptools.backends.legacy:build"

            [project]
            name = "{slug}"
            version = "0.1.0"
            description = "AMC-compatible agent"
            requires-python = ">=3.11"
            dependencies = []

            [tool.pytest.ini_options]
            asyncio_mode = "auto"
        """)


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------

_default_scaffolder: AgentScaffolder | None = None


def get_scaffolder() -> AgentScaffolder:
    global _default_scaffolder
    if _default_scaffolder is None:
        _default_scaffolder = AgentScaffolder()
    return _default_scaffolder


__all__ = [
    "AgentTemplate",
    "ScaffoldFile",
    "ScaffoldProject",
    "AgentScaffolder",
    "get_scaffolder",
]
