apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: amc-studio
  labels:
    app.kubernetes.io/name: amc
    app.kubernetes.io/component: control-plane
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amc-studio
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
