apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: amc-studio
  labels:
    app.kubernetes.io/name: amc
    app.kubernetes.io/component: control-plane
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: amc
      app.kubernetes.io/component: control-plane
