apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amc-workspace
  labels:
    app.kubernetes.io/name: amc
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
