apiVersion: v1
kind: Service
metadata:
  name: amc-studio
  labels:
    app.kubernetes.io/name: amc
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: amc
    app.kubernetes.io/component: control-plane
  ports:
    - name: studio
      port: 3212
      targetPort: studio
    - name: gateway
      port: 3210
      targetPort: gateway
    - name: proxy
      port: 3211
      targetPort: proxy
