{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "amc.fullname" . }}
  labels:
    {{- include "amc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "amc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressPodSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        - protocol: TCP
          port: {{ .Values.service.gatewayPort }}
        - protocol: TCP
          port: {{ .Values.service.proxyPort }}
  egress:
    - to:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.dnsNamespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.dnsPodSelector | nindent 12 }}
      ports:
        {{- range .Values.networkPolicy.dnsPorts }}
        - protocol: UDP
          port: {{ . }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
    {{- if gt (len .Values.networkPolicy.allowedEgressCidrs) 0 }}
    - to:
        {{- range .Values.networkPolicy.allowedEgressCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.allowedEgressPorts }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
