apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bootstrap.vaultPassphraseSecret.name }}
  labels:
    {{- include "amc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bootstrap.vaultPassphraseSecret.key }}: "change-me-vault-passphrase"
  {{ .Values.bootstrap.ownerUsernameSecret.key }}: "owner"
  {{ .Values.bootstrap.ownerPasswordSecret.key }}: "change-me-owner-password"
  {{ .Values.notary.passphraseSecret.key }}: "change-me-notary-passphrase"
  {{ .Values.notary.authSecret.key }}: "change-me-notary-auth-secret"
