[build]
  publish = "website"
  command = ""

[[redirects]]
  from = "/docs"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
